project reorganization: avoid nested projects
pmem/pmemkv-java pull request #102
Opened 2020-12-10 16:53 UTC by KFilipek

- keep flat tree
- target separation

2020-12-11 07:48 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFjuGwE3R12sbGguBa:-MOFjuGwE3R12sbGguBb:b-mvu0qd) (no related file):*
in 'run-build.sh' script we're setting path to jni library. I know it's not the best solution, but it may not work without it (since we don't install it...?)

see: https://github.com/pmem/pmemkv-java/blob/master/utils/docker/run-build.sh#L48

---
___
*[src/main/pom.xml, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFj19L9FoHqeGcyiU5:-MOFj19M-EmHH9kdsg36:bgfs1sh) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L34)):*
> ```XML
> 				<configuration>
> 					<showWarnings>true</showWarnings>
> 					<failOnWarning>false</failOnWarning>
> ```

I believe, in general we want this to be true - as discussed on the meeting - we can try to disable this for different (than 8) java version
___
*[src/main/pom.xml, line 38 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFkC_uDvzlZmATmu-Z:-MOFkC_uDvzlZmATmu-_:bjuges) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L38)):*
> ```XML
> 						<arg>-Xlint:all</arg>
> 					</compilerArgs>
> 					<verbose>true</verbose>
> ```

I'm not sure if this verbose param gives you anything extra - if I remember correctly it's better to set up mvn install command with extra param (`-X` I believe) - to be set here: https://github.com/pmem/pmemkv-java/blob/master/utils/docker/run-build.sh#L41

I've removed this param after debugging to not clutter the output for general purpose.
___
*[src/main/pom.xml, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFkvop1oj-wpSinpIh:-MOFkvoq1T4S9h8NGXlE:b-wixr9p) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L47)):*
> ```XML
> 				<configuration>
> 					<useSystemClassLoader>false</useSystemClassLoader>
> 					<argLine>-Djava.library.path=${project.build.directory}/../cpp/target
> ```

this path changed, I believe
___
*[src/main/pom.xml, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFlDv5EhOJPBTddE46:-MOFlDv5EhOJPBTddE47:b-4bzjgw) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L52)):*
> ```XML
> 			</plugin>
> 			<plugin>
> 				<groupId>org.apache.maven.plugins</groupId>
> ```

out of curiosity - is this required?
___
*[src/main/cpp/pom.xml, line 14 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFi0pe-NQSUNTyAlYM:-MOFi0pfAvgWyYbm4tcD:bot78eu) ([raw file](https://github.com/pmem/pmemkv-java/blob/975d9e3b8c494e968e75671708c537dfebc014a8/src/main/cpp/pom.xml#L14)):*
> ```XML
>     </parent>
>     <groupId>io.pmem</groupId>
>     <artifactId>libpmemkv-jni</artifactId>
> ```

this 'lib' part was required, because so file is generated based on this name - right now this build will create 'pmemkv-jni.so', which then won't be found when looking for jni part


<!-- Sent from Reviewable.io -->

2020-12-14 15:05 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 0 of 30 files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFjuGwE3R12sbGguBa:-MOWm2h2-AtZ2E0-CKF8:b-fgkz29) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in 'run-build.sh' script we're setting path to jni library. I know it's not the best solution, but it may not work without it (since we don't install it...?)

see: https://github.com/pmem/pmemkv-java/blob/master/utils/docker/run-build.sh#L48
</blockquote></details>

Thanks, I will try with installing in local maven repository and getResource.
Done.

---
___
*[src/main/pom.xml, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFj19L9FoHqeGcyiU5:-MOWl3Tt9A5INyFvqDEq:bw4wt5h) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe, in general we want this to be true - as discussed on the meeting - we can try to disable this for different (than 8) java version
</blockquote></details>

I will enable it at the end, now I'm not gonna fight with single warnings or JAVA_HOME variables etc.
___
*[src/main/pom.xml, line 38 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFkC_uDvzlZmATmu-Z:-MOWlDSlAuaVSXTLYZMH:bbvue60) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if this verbose param gives you anything extra - if I remember correctly it's better to set up mvn install command with extra param (`-X` I believe) - to be set here: https://github.com/pmem/pmemkv-java/blob/master/utils/docker/run-build.sh#L41

I've removed this param after debugging to not clutter the output for general purpose.
</blockquote></details>

-X enable full logging, I just wanted to see log of this particular plugin. However, I removed it.
Done.
___
*[src/main/pom.xml, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFkvop1oj-wpSinpIh:-MOWlQuv2m5nqv3jRRdL:b1w0bqi) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this path changed, I believe
</blockquote></details>

Sure, please, keep in mind TODO list, some of those things are not covered yet.
___
*[src/main/pom.xml, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFlDv5EhOJPBTddE46:-MOWlb5f3MBCjulz8Nfh:b-8lkixm) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

out of curiosity - is this required?
</blockquote></details>

Before was necessary,  because of copying. I will remove this plugin after successfully runned tests.
___
*[src/main/cpp/pom.xml, line 14 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFi0pe-NQSUNTyAlYM:-MOWlwH0AFJKpu-t3-Y2:bqxavfn) ([raw file](https://github.com/pmem/pmemkv-java/blob/975d9e3b8c494e968e75671708c537dfebc014a8/src/main/cpp/pom.xml#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this 'lib' part was required, because so file is generated based on this name - right now this build will create 'pmemkv-jni.so', which then won't be found when looking for jni part
</blockquote></details>

I will reorganize it


<!-- Sent from Reviewable.io -->

2020-12-14 21:01 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 0 of 31 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[java-bindings/pom.xml, line 15 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOY2LCeBTR9u0X7yWqx:-MOY2LCeBTR9u0X7yWqy:btq7q7y) ([raw file](https://github.com/pmem/pmemkv-java/blob/b31de023e73c315a10f78d8c55311796c111dc6d/java-bindings/pom.xml#L15)):*
> ```XML
> 	<groupId>io.pmem</groupId>
> 	<artifactId>pmemkv</artifactId>
> 	<name>java-bindings</name>
> ```

will the output jar file named "java-bindings.jar" ?
___
*[src/main/pom.xml, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFkvop1oj-wpSinpIh:-MOY1mZM3_sbTf65BUGP:b-uonp5l) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L47)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Sure, please, keep in mind TODO list, some of those things are not covered yet.
</blockquote></details>

yeah, I got this; just trying to point you what you may (or may not) miss while fixing this crazy pom-world ;)

also, perhaps make use of some of these vars (like: `${project.build.directory}`)
___
*[src/main/pom.xml, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFlDv5EhOJPBTddE46:-MOY24qQChedIMNZ_Mwp:b-k5e7xy) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L52)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Before was necessary,  because of copying. I will remove this plugin after successfully runned tests.
</blockquote></details>

I meant the "groupId" field - is that necessary when using a plugin..?


<!-- Sent from Reviewable.io -->

2020-12-16 07:03 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 1 of 31 files reviewed, 6 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[java-bindings/pom.xml, line 43 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOeLXAb7rvNwziL5epG:-MOeLXAc6YVdNmU_md4p:bgvd8vm) ([raw file](https://github.com/pmem/pmemkv-java/blob/01a982f7d14da898628149f22026ff30d158eb9a/java-bindings/pom.xml#L43)):*
> ```XML
> 			</plugin>
> 			<plugin>
> 				<groupId>org.apache.maven.plugins</groupId>
> ```

if you won't copy anything (the copy itself is removed), I believe this plugin can be removed, too


<!-- Sent from Reviewable.io -->

2020-12-16 12:17 UTC, karczex reviewed
"java-bindings" and "jni-bindings" seems to be little bit to verbose, as you have paths like "pmemkv-java/java-bindings". Probably names "jni" and "binding" would be enough. 

> Reviewed 1 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102#-:-MOfQbKx4TgGT1sdZM4Z:b-szyrap)* status: 2 of 31 files reviewed, 8 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[java-bindings/pom.xml, line 15 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOfRw4X4HCfhSas7gan:-MOfRw4X4HCfhSas7gao:b-tcv9il) ([raw file](https://github.com/pmem/pmemkv-java/blob/01a982f7d14da898628149f22026ff30d158eb9a/java-bindings/pom.xml#L15)):*
> ```XML
> 	<groupId>io.pmem</groupId>
> 	<artifactId>pmemkv</artifactId>
> 	<name>java-bindings</name>
> ```

pmemkv-binding  - This project do not bind java to anything (and it's only one binding) 
___
*[java-bindings/pom.xml, line 17 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOfS_7Q37DE1jivvHec:-MOfS_7Q37DE1jivvHed:b-jafo3k) ([raw file](https://github.com/pmem/pmemkv-java/blob/01a982f7d14da898628149f22026ff30d158eb9a/java-bindings/pom.xml#L17)):*
> ```XML
> 	<name>java-bindings</name>
> 	<packaging>jar</packaging>
> 	<description>Java code and main package for pmemkv Java bindings</description>
> ```

binding 
___
*[src/main/pom.xml, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFj19L9FoHqeGcyiU5:-MOfSm_B2248GMGHkfp2:b-yv4urw) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L34)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I will enable it at the end, now I'm not gonna fight with single warnings or JAVA_HOME variables etc.
</blockquote></details>

I'm not sure any more if we should enable it, as it prevents us from building with higher versions of java. 
At best (I don't know if it's possible) we should enable it only for some CI builds, or somehow disable warning about java version. 


<!-- Sent from Reviewable.io -->

2020-12-22 13:46 UTC, KFilipek reviewed
> Reviewed 15 of 26 files at r2, 6 of 18 files at r4, 1 of 24 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 4 of 43 files reviewed, 6 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[java-bindings/pom.xml, line 15 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOY2LCeBTR9u0X7yWqx:-MP9ghFu14XO-mAk4Rlt:bghygu4) ([raw file](https://github.com/pmem/pmemkv-java/blob/b31de023e73c315a10f78d8c55311796c111dc6d/java-bindings/pom.xml#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

will the output jar file named "java-bindings.jar" ?
</blockquote></details>

Just artifactId is using to package name
___
*[java-bindings/pom.xml, line 15 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOfRw4X4HCfhSas7gan:-MP9glxW9S5CkB_Xf87o:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/01a982f7d14da898628149f22026ff30d158eb9a/java-bindings/pom.xml#L15)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

pmemkv-binding  - This project do not bind java to anything (and it's only one binding) 
</blockquote></details>

Done.
___
*[java-bindings/pom.xml, line 17 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOfS_7Q37DE1jivvHec:-MP9goi34rtesP7E_TZ5:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/01a982f7d14da898628149f22026ff30d158eb9a/java-bindings/pom.xml#L17)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

binding 
</blockquote></details>

Done.
___
*[java-bindings/pom.xml, line 43 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOeLXAb7rvNwziL5epG:-MP9dqCc-7vNI9BaTz9_:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/01a982f7d14da898628149f22026ff30d158eb9a/java-bindings/pom.xml#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you won't copy anything (the copy itself is removed), I believe this plugin can be removed, too
</blockquote></details>

Done.
___
*[src/main/pom.xml, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFj19L9FoHqeGcyiU5:-MP9duXB7jsFZyai2ljX:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L34)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I'm not sure any more if we should enable it, as it prevents us from building with higher versions of java. 
At best (I don't know if it's possible) we should enable it only for some CI builds, or somehow disable warning about java version. 
</blockquote></details>

Done.
___
*[src/main/cpp/pom.xml, line 14 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFi0pe-NQSUNTyAlYM:-MP9do9g-6ge_O2XnMFk:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/975d9e3b8c494e968e75671708c537dfebc014a8/src/main/cpp/pom.xml#L14)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I will reorganize it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-22 13:53 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 3 of 43 files reviewed, 9 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 523 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MP9i2irA1YOZp8eMTwk:-MP9i2irA1YOZp8eMTwl:b-hjsfap) ([raw file](https://github.com/pmem/pmemkv-java/blob/6bbb4ac6cabdcc096be0dfc249db03b52599b64a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L523)):*
> ```Java
> 				if (is == null) {
> 					try {
> 						throw new Exception("Cannot get resource from Jar file.");
> ```

I think this try/catch is not needed. You can just print the error if (is == null)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 529 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MP9i86yC70ClSAHBZNf:-MP9i86yC70ClSAHBZNg:b-st4oz5) ([raw file](https://github.com/pmem/pmemkv-java/blob/6bbb4ac6cabdcc096be0dfc249db03b52599b64a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L529)):*
> ```Java
> 				}
> 
> 				File file;
> ```

this whole block should be in else{} block. Otherwise if is == null we will just print the error and this will be exeucuted anyway.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 542 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MP9iGupDjCpVg5lXs7k:-MP9iGupDjCpVg5lXs7l:b-xx9019) ([raw file](https://github.com/pmem/pmemkv-java/blob/6bbb4ac6cabdcc096be0dfc249db03b52599b64a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L542)):*
> ```Java
> 					os.close();
> 
> 					System.load(file.getAbsolutePath());
> ```

Shouldn't we cleanup the temporary file here? (I'm not sure what is the general approach with temp files in java)


<!-- Sent from Reviewable.io -->

2020-12-22 14:41 UTC, KFilipek reviewed
> Reviewed 1 of 24 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 4 of 43 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 523 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MP9i2irA1YOZp8eMTwk:-MP9sHFB-e8oNt0L4--W:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/6bbb4ac6cabdcc096be0dfc249db03b52599b64a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L523)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think this try/catch is not needed. You can just print the error if (is == null)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 529 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MP9i86yC70ClSAHBZNf:-MP9sGEc2hdSu6mAFtw2:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/6bbb4ac6cabdcc096be0dfc249db03b52599b64a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L529)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this whole block should be in else{} block. Otherwise if is == null we will just print the error and this will be exeucuted anyway.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-23 12:52 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 26 files at r2, 3 of 18 files at r4, 16 of 24 files at r5, 1 of 1 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 22 of 43 files reviewed, 13 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pom.xml, line 24 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPE_6Bu4kM0zoLwizAb:-MPE_6Bu4kM0zoLwizAc:b9nb7qh) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pom.xml#L24)):*
> ```XML
>     <modules>
>         <module>jni-bindings</module> <!-- pom for jni part -->
>         <module>pmemkv-binding</module> <!-- pom for java part -->
> ```

why here `binding` and above `bindings`?
___
*[pom.xml, line 25 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPE_A_40cCOjlDhkq1j:-MPE_A_40cCOjlDhkq1k:bgyqqdz) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pom.xml#L25)):*
> ```XML
>         <module>jni-bindings</module> <!-- pom for jni part -->
>         <module>pmemkv-binding</module> <!-- pom for java part -->
>         <module>pmemkv-examples</module> <!-- pom for examples part -->
> ```

pls specify: for java examples
___
*[pmemkv-examples/README.md, line 36 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPE_vpd671F7XtRcNd_:-MPE_vpd671F7XtRcNda:b-a5n4pt) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/README.md#L36)):*
> ```Markdown
> ```
> ```

redundant empty line(s)
___
*[java-bindings/pom.xml, line 43 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOeLXAb7rvNwziL5epG:-MPEcqtj-bDsOaXi0rAo:bo4f1en) ([raw file](https://github.com/pmem/pmemkv-java/blob/01a982f7d14da898628149f22026ff30d158eb9a/java-bindings/pom.xml#L43)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not removed (unless you need this plugin for something else, then ofcoz it can stay ;) )
___
*[pmemkv-binding/pom.xml, line 24 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEc76y8Ej9Lbu2aaTl:-MPEc76y8Ej9Lbu2aaTm:b-pw62v7) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/pom.xml#L24)):*
> ```XML
> 				<directory>../jni-bindings/target/</directory>
> 				<includes>
> 					<include>libpmemkv-jni.so.1</include>
> ```

can you use the `soversion` property from jni's pom file?
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 517 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEaL-b6tNYoR8piPPJ:-MPEaL-b6tNYoR8piPPK:botgkvr) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L517)):*
> ```Java
> 
> 		static {
> 			boolean unsatisfied_error = false;
> ```

maybe this change in loading jni lib should be in sep. commit...?
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 524 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEaoGmAxMXRSfbejwY:-MPEaoGmAxMXRSfbejwZ:buwpogw) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L524)):*
> ```Java
> 			}
> 			if (unsatisfied_error) {
> 				InputStream is = Database.class.getResourceAsStream("/libpmemkv-jni.so.1");
> ```

this `1` should perhaps be a variable...? in jni pom file we have property for that (`soversion`)... or maybe I'm just being picky... ;) 
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetAllBufferJNICallback.java, line 2 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEboiO2IiLLfU1Q_vg:-MPEboiO2IiLLfU1Q_vh:bald82q) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetAllBufferJNICallback.java#L2)):*
> ```Java
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2017-2019, Intel Corporation */
> ```

if you change the content update the license date ;)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetKeysBuffersJNICallback.java, line 2 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEbi9J1OaviOra1cvE:-MPEbi9J1OaviOra1cvF:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetKeysBuffersJNICallback.java#L2)):*
> ```Java
> // SPDX-License-Identifier: BSD-3-Clause
> // Copyright 2017-2019, Intel Corporation
> ```

.
___
*[src/main/pom.xml, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFj19L9FoHqeGcyiU5:-MPEcLLDBlBy6J7JYnln:bnqdu9w) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L34)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

hmm maybe as karczex said, we could enable this only on CI builds... It will not annoy anyone with different Java (and probably other warnings on their system) and it will be checked on CI, so we'll have this checked *somewhere*


<!-- Sent from Reviewable.io -->

2020-12-23 13:04 UTC, lukaszstolarczuk requested changes
> Reviewed 5 of 8 files at r1, 9 of 18 files at r4, 6 of 24 files at r5, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: all files reviewed, 26 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-examples/pom.xml, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEg_zwBmo9O7qrBO6c:-MPEg_zx7lT4b5elDRA8:b-m0f1oq) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/pom.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

can this directory be called just "examples" (instead of "pmemkv-examples")?
___
*[pmemkv-examples/pom.xml, line 11 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEez5H521OsSftUU63:-MPEez5H521OsSftUU64:bs1xxyc) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/pom.xml#L11)):*
> ```XML
>     <version>1.0.0</version>
>     <packaging>pom</packaging>
> ```

it's not dependent from pmemkv-root?
___
*[pmemkv-examples/pom.xml, line 26 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEeqL404k0wVa8qnJi:-MPEeqL404k0wVa8qnJj:bw0wpjl) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/pom.xml#L26)):*
> ```XML
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>     </properties>
> </project>
> ```

no new line at the end
___
*[pmemkv-examples/ByteBufferExample/pom.xml, line 18 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEf8u79OTqhiVwwnS_:-MPEf8u79OTqhiVwwnSa:b8jjen5) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/ByteBufferExample/pom.xml#L18)):*
> ```XML
>     <name>ByteBufferExample</name>
>     <packaging>jar</packaging>
>     <!--    <description>Java code and main package for pmemkv Java bindings</description>-->
> ```

either put proper description or remove this pls
___
*[pmemkv-examples/MixedTypesExample/pom.xml, line 75 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfkQF8ZshoEFOeUCk:-MPEfkQF8ZshoEFOeUCl:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/MixedTypesExample/pom.xml#L75)):*
> ```XML
>         </dependency>
>     </dependencies>
> </project>
> ```

.
___
*[pmemkv-examples/PicturesExample/pom.xml, line 75 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfqKA0-I8ms-FKk4r:-MPEfqKA0-I8ms-FKk4s:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/PicturesExample/pom.xml#L75)):*
> ```XML
>         </dependency>
>     </dependencies>
> </project>
> ```

.
___
*[pmemkv-examples/StringExample/pom.xml, line 75 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfyH7CuvPG7e1zl2e:-MPEfyH7CuvPG7e1zl2f:b-nsqcu9) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/StringExample/pom.xml#L75)):*
> ```XML
>         </dependency>
>     </dependencies>
>     
> ```

redundant empty line
___
*[pmemkv-examples/StringExample/pom.xml, line 76 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfzVR50oZfQqNdyx4:-MPEfzVR50oZfQqNdyx5:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/StringExample/pom.xml#L76)):*
> ```XML
>     </dependencies>
>     
> </project>
> ```

.
___
*[utils/docker/run-build.sh, line 17 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEgQcw1TWlpq_Pa40t:-MPEgQcw1TWlpq_Pa40u:bwsv1co) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/utils/docker/run-build.sh#L17)):*
> ```Shell
> 	example_name=$1
> 	jar_path=../pmemkv-binding/target/pmemkv-1.0.0.jar
>   example_path=`find .. | grep -P '\b(?!pmemkv)\b([a-zA-Z]+)\-([0-9.]+)\.jar' | grep ${example_name}`
> ```

this is a bit crazy line ;) pls add a comment
___
*[utils/docker/run-build.sh, line 56 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEg7Qm0nDIxRbKoFpU:-MPEg7Qm0nDIxRbKoFpV:bb1rlzo) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/utils/docker/run-build.sh#L56)):*
> ```Shell
> if [[ "$AUTO_DOC_UPDATE" == "1" ]]; then
> 	echo "Running auto doc update"
> 	$SCRIPTSDIR/run-doc-update.sh
> ```

pls try and check if documentation is still properly built
___
*[pmemkv-binding/pom.xml, line 61 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfRbBD_hfkrCv5kMg:-MPEfRbBD_hfkrCv5kMh:b4q7mtg) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/pom.xml#L61)):*
> ```XML
> 			</plugin>
> 		</plugins>
> 	</build>
> ```

we don't need version.properties here anymore?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEeYFx9ZjBHlWIOEG-:-MPEeYFx9ZjBHlWIOEG0:bfjdflb) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java#L1)):*
> ```Java
> // SPDX-License-Identifier: BSD-3-Clause
> ```

hmm since there's `tests` in the file path maybe we can drop the "initial" `test` directory...?
___
*[pmemkv-examples/PicturesExample/src/main/java/PicturesExample.java, line 82 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfttpAXYIE0xFuo1A:-MPEfttpAXYIE0xFuo1B:b-75ywm7) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/PicturesExample/src/main/java/PicturesExample.java#L82)):*
> ```Java
> 	private Database<String, BufferedImage> db;
> 	private String engine = "cmap";
> 	static final long serialVersionUID = 9101254512891724823L;
> ```

why is this needed?


<!-- Sent from Reviewable.io -->

2020-12-23 13:56 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 33 of 43 files reviewed, 26 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pom.xml, line 24 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPE_6Bu4kM0zoLwizAb:-MPEjy2pAqzEZ_e-f9vk:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pom.xml#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why here `binding` and above `bindings`?
</blockquote></details>

Done.
___
*[pom.xml, line 25 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPE_A_40cCOjlDhkq1j:-MPEgb199396mIbjstxV:b-cb6j4o) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pom.xml#L25)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls specify: for java examples
</blockquote></details>

Karczex point was to be not too verbose, it's why java-binding was changed to pmemkv-binding
Done.
___
*[pmemkv-examples/README.md, line 36 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPE_vpd671F7XtRcNd_:-MPEgPedEP3DFR-kJnPl:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/README.md#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line(s)
</blockquote></details>

Done.
___
*[java-bindings/pom.xml, line 43 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOeLXAb7rvNwziL5epG:-MPEl4rFC8LJ0Kr_hAYo:buketii) ([raw file](https://github.com/pmem/pmemkv-java/blob/01a982f7d14da898628149f22026ff30d158eb9a/java-bindings/pom.xml#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not removed (unless you need this plugin for something else, then ofcoz it can stay ;) )
</blockquote></details>

Indeed
___
*[pmemkv-binding/pom.xml, line 24 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEc76y8Ej9Lbu2aaTl:-MPElexEEi6t2Wxi2R2W:bpb2qq8) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/pom.xml#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you use the `soversion` property from jni's pom file?
</blockquote></details>

It should require some tricky searching through modules and filtering. I can do this in separate PR to not block
___
*[pmemkv-binding/pom.xml, line 61 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfRbBD_hfkrCv5kMg:-MPElTjB5wrvffumXd7P:brgbv10) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/pom.xml#L61)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we don't need version.properties here anymore?
</blockquote></details>

It was never used, probably someone need it for using in Java code, it will be needed further, in separate PR
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 524 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEaoGmAxMXRSfbejwY:-MPEm6PHDrA6fa372LtO:b-8a05gs) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L524)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this `1` should perhaps be a variable...? in jni pom file we have property for that (`soversion`)... or maybe I'm just being picky... ;) 
</blockquote></details>

As above
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetAllBufferJNICallback.java, line 2 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEboiO2IiLLfU1Q_vg:-MPEgC8V3gW_p51Z7Rg_:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetAllBufferJNICallback.java#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you change the content update the license date ;)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetKeysBuffersJNICallback.java, line 2 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEbi9J1OaviOra1cvE:-MPEgFJ13y3ulCU5-dRp:b3jqhms) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetKeysBuffersJNICallback.java#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

I didn't touch body of this file.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEeYFx9ZjBHlWIOEG-:-MPEqZQQEW7KNH40JxOY:b7ut6zf) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm since there's `tests` in the file path maybe we can drop the "initial" `test` directory...?
</blockquote></details>

Nope, it's classic Java/Maven directory order, https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
___
*[src/main/pom.xml, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFj19L9FoHqeGcyiU5:-MPEkJmT3ZJz7limtJ1u:bbdc04o) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm maybe as karczex said, we could enable this only on CI builds... It will not annoy anyone with different Java (and probably other warnings on their system) and it will be checked on CI, so we'll have this checked *somewhere*
</blockquote></details>

Could you open GitHub issue? I think it should be connected with finalize() deprecation, I think it will be related with some changes in code logic. In Java >8 we get warning about deprecation. This PR is mainly for reorganization.


<!-- Sent from Reviewable.io -->

2020-12-28 10:10 UTC, karczex commented
___
*[pmemkv-examples/pom.xml, line 11 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEez5H521OsSftUU63:-MPcp00-EceWxBbyqlyB:bsilxvf) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/pom.xml#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's not dependent from pmemkv-root?
</blockquote></details>

It shouldn't  be


<!-- Sent from Reviewable.io -->

2020-12-28 10:35 UTC, karczex commented
___
*[pmemkv-examples/PicturesExample/src/main/java/PicturesExample.java, line 82 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfttpAXYIE0xFuo1A:-MPcrXSj3gidoM3nKmyk:b-7r7b1v) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/PicturesExample/src/main/java/PicturesExample.java#L82)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>


 It may be removed, as this ID may be generated in runtime by JVM


<!-- Sent from Reviewable.io -->

2020-12-28 14:17 UTC, lukaszstolarczuk requested changes
> Reviewed 10 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: all files reviewed, 15 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 517 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEaL-b6tNYoR8piPPJ:-MPdcC0g4Y27tXeaolcP:b-ytrvpv) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L517)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe this change in loading jni lib should be in sep. commit...?
</blockquote></details>

there's something wrong with this new commit: https://github.com/pmem/pmemkv-java/pull/102/commits/7865e6ed499d9692d172682bb9df37b92cc8e534
it includes the whole DB file
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 524 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEaoGmAxMXRSfbejwY:-MPdcJig-kwIxyw9aKUL:bapzq6t) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L524)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

As above
</blockquote></details>

I get that you don't want to parse it from pom file, maybe just a new variable (within this file)?
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetKeysBuffersJNICallback.java, line 2 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEbi9J1OaviOra1cvE:-MPdcVQX7xfzeTkz8IAx:b-gscjm2) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetKeysBuffersJNICallback.java#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I didn't touch body of this file.
</blockquote></details>

reviewable seems to disagree (changed license comment and removed two lines at the bottom of this file)
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEeYFx9ZjBHlWIOEG-:-MPdd5XH0lr4qV3Em8MG:b8jwtkm) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java#L1)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Nope, it's classic Java/Maven directory order, https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
</blockquote></details>

ok, make sens, but then, according to your link I believe we should drop the second `tests` dir.
we don't have `src/main/java/io/pmem/pmemkv/**src**` so here we shouldn't have `src/test/java/io/pmem/pmemkv/**tests**` ;)
___
*[src/main/pom.xml, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MOFj19L9FoHqeGcyiU5:-MPdbNmkCV-HX8qkQOW2:b-yc8msb) ([raw file](https://github.com/pmem/pmemkv-java/blob/758e692b2e4302aa025479a1f656eba79abf7c5c/src/main/pom.xml#L34)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Could you open GitHub issue? I think it should be connected with finalize() deprecation, I think it will be related with some changes in code logic. In Java >8 we get warning about deprecation. This PR is mainly for reorganization.
</blockquote></details>

couldn't you open it? :P
I've updated our old issue about java version


<!-- Sent from Reviewable.io -->

2020-12-30 14:33 UTC, KFilipek reviewed
> Reviewed 1 of 18 files at r4, 17 of 24 files at r5, 2 of 2 files at r7, 9 of 10 files at r8, 16 of 21 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 39 of 42 files reviewed, 15 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-examples/pom.xml, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEg_zwBmo9O7qrBO6c:-MPnZmxLDXfteCHvbtQN:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/pom.xml#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can this directory be called just "examples" (instead of "pmemkv-examples")?
</blockquote></details>

Done.
___
*[pmemkv-examples/pom.xml, line 26 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEeqL404k0wVa8qnJi:-MPnZwOS44hRQ98KnXpd:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/pom.xml#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no new line at the end
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 17 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEgQcw1TWlpq_Pa40t:-MPo1Wm8BfGnviwqFAy8:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/utils/docker/run-build.sh#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this is a bit crazy line ;) pls add a comment
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 56 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEg7Qm0nDIxRbKoFpU:-MPo1B1xBNQj6xIDH1Y4:bwn0l37) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/utils/docker/run-build.sh#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls try and check if documentation is still properly built
</blockquote></details>

Done.
I've run mvn command from this file and documentation was generated under:
pmemkv-java/pmemkv-binding/target/site/apidocs/io/pmem/pmemkv/class-use/KeyCallback.html
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 517 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEaL-b6tNYoR8piPPJ:-MPieXOM9oDL-xfw4wth:bxy3ohj) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L517)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there's something wrong with this new commit: https://github.com/pmem/pmemkv-java/pull/102/commits/7865e6ed499d9692d172682bb9df37b92cc8e534
it includes the whole DB file
</blockquote></details>

I removed staged file from previous commit and made another one.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 524 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEaoGmAxMXRSfbejwY:-MPidNzgAD8J4gjfBM5m:bqx8638) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L524)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I get that you don't want to parse it from pom file, maybe just a new variable (within this file)?
</blockquote></details>

It's used only in one place. Anyway, I opened the issue will cover this case.
https://github.com/pmem/pmemkv-java/issues/103 
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetKeysBuffersJNICallback.java, line 2 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEbi9J1OaviOra1cvE:-MPiezal-mPiZ_P6DeXA:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/internal/GetKeysBuffersJNICallback.java#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

reviewable seems to disagree (changed license comment and removed two lines at the bottom of this file)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEeYFx9ZjBHlWIOEG-:-MPijb3T-WJNkg1XHwYs:bsi946b) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

ok, make sens, but then, according to your link I believe we should drop the second `tests` dir.
we don't have `src/main/java/io/pmem/pmemkv/**src**` so here we shouldn't have `src/test/java/io/pmem/pmemkv/**tests**` ;)
</blockquote></details>

Everything after src/main/(java/test) is the package name, as in this case:
package io.pmem.pmemkv.tests;
Package purpose is to isolate classes from the other.
Anyway, changed.
___
*[pmemkv-examples/ByteBufferExample/pom.xml, line 18 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEf8u79OTqhiVwwnS_:-MPnsXaJ-L1vXSaDCdEX:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/ByteBufferExample/pom.xml#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

either put proper description or remove this pls
</blockquote></details>

Done.
___
*[pmemkv-examples/MixedTypesExample/pom.xml, line 75 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfkQF8ZshoEFOeUCk:-MPnsfBq0t77I9sudRzU:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/MixedTypesExample/pom.xml#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[pmemkv-examples/PicturesExample/pom.xml, line 75 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfqKA0-I8ms-FKk4r:-MPnsi768f8AWVLfej_z:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/PicturesExample/pom.xml#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[pmemkv-examples/PicturesExample/src/main/java/PicturesExample.java, line 82 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfttpAXYIE0xFuo1A:-MPnslpJ6j-WDXw578x3:b-hbxuz4) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/PicturesExample/src/main/java/PicturesExample.java#L82)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

 It may be removed, as this ID may be generated in runtime by JVM
</blockquote></details>

It caused warning, also IDE suggest to add this. If we want to treat warnings as errors, every warning should be solved. Finalize is the next one.
___
*[pmemkv-examples/StringExample/pom.xml, line 75 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfyH7CuvPG7e1zl2e:-MPntwGKCwtWRKjxk4fe:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/StringExample/pom.xml#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[pmemkv-examples/StringExample/pom.xml, line 76 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfzVR50oZfQqNdyx4:-MPntwUF4PcFviOxJZuU:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3 [...]

2020-12-31 09:41 UTC, lukaszstolarczuk requested changes
> Reviewed 20 of 21 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[pom.xml, line 35 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPs6BqCBC-UjjKUfhCX:-MPs6BqCBC-UjjKUfhCY:bmpqlyn) ([raw file](https://github.com/pmem/pmemkv-java/blob/bfd8114b4e3756cfa6d4c4f44af1e48903f20b7b/pom.xml#L35)):*
> ```XML
>           <version>2.11.0</version>
>           <configuration>
>             <configFile>${pom.basedir}/eclipse-formatter-config.xml</configFile>
> ```

not `/utils` ?
___
*[README.md, line 74 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPs6_Pn0Eb1ak8dJwxN:-MPs6_Pn0Eb1ak8dJwxO:bl46n53) ([raw file](https://github.com/pmem/pmemkv-java/blob/bfd8114b4e3756cfa6d4c4f44af1e48903f20b7b/README.md#L74)):*
> ```Markdown
> in examples.
> 
> Examples can be found within this repository in [examples directory](https://github.com/pmem/pmemkv-java/tree/master/pmemkv-examples).
> ```

changed examples dir
___
*[utils/docker/run-build.sh, line 56 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEg7Qm0nDIxRbKoFpU:-MPs3XEYA9S2G2bsLyg2:b9y27z0) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/utils/docker/run-build.sh#L56)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
I've run mvn command from this file and documentation was generated under:
pmemkv-java/pmemkv-binding/target/site/apidocs/io/pmem/pmemkv/class-use/KeyCallback.html
</blockquote></details>

great, thanks!
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 517 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEaL-b6tNYoR8piPPJ:-MPs1x3rBDNzdBxOIbIw:b8tbhrz) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L517)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I removed staged file from previous commit and made another one.
</blockquote></details>

still something's wrong:
https://github.com/pmem/pmemkv-java/pull/102/commits/bfd8114b4e3756cfa6d4c4f44af1e48903f20b7b
now only date is changed in that commit
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEeYFx9ZjBHlWIOEG-:-MPs2Jfz1HX9X8N1AB4t:b-nj8oxt) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java#L1)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Everything after src/main/(java/test) is the package name, as in this case:
package io.pmem.pmemkv.tests;
Package purpose is to isolate classes from the other.
Anyway, changed.
</blockquote></details>

hmm.. I didn't think of that - if you're ok with this package being changed (to the one without "tests") then ok, but if you disagree then my comment can go to trash and we can have it back to previous state ;)
___
*[pmemkv-examples/PicturesExample/src/main/java/PicturesExample.java, line 82 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfttpAXYIE0xFuo1A:-MPs7CKB13e96dEEdZEi:b-wpqftv) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/PicturesExample/src/main/java/PicturesExample.java#L82)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It caused warning, also IDE suggest to add this. If we want to treat warnings as errors, every warning should be solved. Finalize is the next one.
</blockquote></details>

if you want to leave it, then make it a sep. commit - it should not belong to the one cleaning up the pom files ;)


<!-- Sent from Reviewable.io -->

2020-12-31 12:43 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102)* status: 40 of 42 files reviewed, 6 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[pom.xml, line 35 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPs6BqCBC-UjjKUfhCX:-MPsbPyR43MoFiCIO1yY:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/bfd8114b4e3756cfa6d4c4f44af1e48903f20b7b/pom.xml#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not `/utils` ?
</blockquote></details>

Done.
___
*[README.md, line 74 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPs6_Pn0Eb1ak8dJwxN:-MPsb_mJ00ByoRQrFla4:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/bfd8114b4e3756cfa6d4c4f44af1e48903f20b7b/README.md#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

changed examples dir
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 517 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEaL-b6tNYoR8piPPJ:-MPsoiOa5KJjs4i24Bh1:bqjjg7b) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L517)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

still something's wrong:
https://github.com/pmem/pmemkv-java/pull/102/commits/bfd8114b4e3756cfa6d4c4f44af1e48903f20b7b
now only date is changed in that commit
</blockquote></details>

Done.
Check this out
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEeYFx9ZjBHlWIOEG-:-MPsg_-X0n47OlpAq734:bltsbh0) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. I didn't think of that - if you're ok with this package being changed (to the one without "tests") then ok, but if you disagree then my comment can go to trash and we can have it back to previous state ;)
</blockquote></details>

I've done some reconnaissance in this area, tests and sources should have the same package naming, but when you write unit tests for method xyz, the proper naming for testing is xyzTest.
___
*[pmemkv-examples/PicturesExample/src/main/java/PicturesExample.java, line 82 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEfttpAXYIE0xFuo1A:-MPsoex83HN-eew8gT9p:b-nd9dmb) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-examples/PicturesExample/src/main/java/PicturesExample.java#L82)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if you want to leave it, then make it a sep. commit - it should not belong to the one cleaning up the pom files ;)
</blockquote></details>

Done.
Now should be okey


<!-- Sent from Reviewable.io -->

2020-12-31 14:07 UTC, lukaszstolarczuk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/102#-:-MPt6tUc6IS3Y_RDmiOM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java, line 1 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/102#-MPEeYFx9ZjBHlWIOEG-:-MPt604pAzuPW8dnM5hW:b-9zamcj) ([raw file](https://github.com/pmem/pmemkv-java/blob/b453974d9b7f3fd1e0a52a3f68eb2505cd4ee006/pmemkv-binding/src/test/java/io/pmem/pmemkv/tests/CmapTest.java#L1)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I've done some reconnaissance in this area, tests and sources should have the same package naming, but when you write unit tests for method xyz, the proper naming for testing is xyzTest.
</blockquote></details>

I see. I guess, that's okaaay for us. "cmapTest" seems like a reasonable name for our tests for the selected engine (which is a functionality in a way..) :)


<!-- Sent from Reviewable.io -->

2020-12-31 14:07 UTC, merged