[java] fix finalize crash
pmem/pmemkv-java pull request #130
Opened 2021-03-01 20:21 UTC by KFilipek

I was tested many cases and after few hours I decided to remove finalize() method.
First of all, I don't know how unique_pointer treat passed config, but please take a look for a following:
1. We invoke Builder->build()
2. new Database() object is now creating
3. database_start() is invoked with pmemkv_open() under the hood (this fails). First thing it does is to wrap config with unique_pointer.
4. Previously: finalize() tried to free config.

I'm planning to rewrite pmemkv internals responsible for creating engines and then more control about resources will be achieved.
Would be good to have config reusable, then only additional parameter would be set when opening/creating failed, but generally it's now impossible due to destroing config on pmemkv side.

2021-03-02 09:50 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 413 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUmK2mdBZzB3rmh3Tua:-MUmK2mdBZzB3rmh3Tub:b-vl5ej2) ([raw file](https://github.com/pmem/pmemkv-java/blob/756f006044607428caeab55e653d01af9a965755/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L413)):*
> ```Java
> 		 *
> 		 */
> 		public void release() {
> ```

Hm, but now, there is a possible leak - in case when you did not call build() at all. I think we should still have a finalize (or some replacement from java 11 in future) - the only thing we should change is the build() function.

In build() You can just move setting `config = 0` *before* returning new `Database(this)`. This way, we will guarantee that config is not deleted after it was passed to pmemkv_open.


<!-- Sent from Reviewable.io -->

2021-03-02 10:03 UTC, igchor reviewed
@kfilipek feel free to propose some alternative API for config but keep in mind we need to support create configs from json. And it get's tricky if you would like to move reponsibility to destroy the config to user. The reason is that config created from json can contain some other objects which must be deallocated (e.g. nested configs are allowed). 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130#-:-MUmLHDW6g5rrzfSJ2Ia:b-rg9ac4)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-03-02 13:07 UTC, KFilipek reviewed
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 413 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUmK2mdBZzB3rmh3Tua:-MUn28La7Y-kKHy2XYTs:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/756f006044607428caeab55e653d01af9a965755/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L413)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, but now, there is a possible leak - in case when you did not call build() at all. I think we should still have a finalize (or some replacement from java 11 in future) - the only thing we should change is the build() function.

In build() You can just move setting `config = 0` *before* returning new `Database(this)`. This way, we will guarantee that config is not deleted after it was passed to pmemkv_open.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-02 17:35 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 2 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUnzpfw0xC6gqJ1tZMr:-MUnzpfw0xC6gqJ1tZMs:bb6ht36) ([raw file](https://github.com/pmem/pmemkv-java/blob/890796822ee7c5e6ed5da048fd0a895aa78559de/jni-binding/io_pmem_pmemkv_Database.cpp#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2017-2020, Intel Corporation */
> ```

2021
___
*[jni-binding/io_pmem_pmemkv_Database_Builder.cpp, line 2 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUnzu_A3qujpMQZCSlY:-MUnzu_A3qujpMQZCSlZ:b-ju2xzj) ([raw file](https://github.com/pmem/pmemkv-java/blob/890796822ee7c5e6ed5da048fd0a895aa78559de/jni-binding/io_pmem_pmemkv_Database_Builder.cpp#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

.
(pls fix them all)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 411 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUo-05wAUK4aFMa9VpE:-MUo-05wAUK4aFMa9VpF:b-kme3xc) ([raw file](https://github.com/pmem/pmemkv-java/blob/890796822ee7c5e6ed5da048fd0a895aa78559de/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L411)):*
> ```Java
> 		/**
> 		 * Frees underlying resources.
> 		 *
> ```

redundant empty comment line
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 465 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUo-85c1msckrNSBz9M:-MUo-85c1msckrNSBz9N:bg2sors) ([raw file](https://github.com/pmem/pmemkv-java/blob/890796822ee7c5e6ed5da048fd0a895aa78559de/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L465)):*
> ```Java
> 		 */
> 		public Database<K, V> build() {
> 			/* Engine takes config ownership */
> ```

`config's ownership`


<!-- Sent from Reviewable.io -->

2021-03-02 17:59 UTC, KFilipek reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 2 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUnzpfw0xC6gqJ1tZMr:-MUo4V2T1vBBTmcikybq:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/890796822ee7c5e6ed5da048fd0a895aa78559de/jni-binding/io_pmem_pmemkv_Database.cpp#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database_Builder.cpp, line 2 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUnzu_A3qujpMQZCSlY:-MUo4VbG9mFM9oPLeSU9:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/890796822ee7c5e6ed5da048fd0a895aa78559de/jni-binding/io_pmem_pmemkv_Database_Builder.cpp#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
(pls fix them all)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 411 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUo-05wAUK4aFMa9VpE:-MUo4z1Q4-RFUi1mQzqe:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/890796822ee7c5e6ed5da048fd0a895aa78559de/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L411)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty comment line
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 465 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUo-85c1msckrNSBz9M:-MUo51h44ioKjZKH1Yyh:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/890796822ee7c5e6ed5da048fd0a895aa78559de/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L465)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`config's ownership`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-02 18:13 UTC, lukaszstolarczuk reviewed
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUo5qcb5wtVdX13qMfW:-MUo5qcb5wtVdX13qMfX:b-kl35g2) (no related file):*
hmm, didn't we want this on stable branch...?

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUo603_0_zI-lwoHwgF:-MUo603_0_zI-lwoHwgG:b-wq0emp) (no related file):*
and perhaps pls extend commit message a little

---


<!-- Sent from Reviewable.io -->

2021-03-02 18:18 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUo5qcb5wtVdX13qMfW:-MUo9LZLCVoWpbtl3PPp:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm, didn't we want this on stable branch...?
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUo603_0_zI-lwoHwgF:-MUo9Lqw05xoFNknaJM4:b-rbq6k9) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and perhaps pls extend commit message a little
</blockquote></details>

Done.
I've added short comment about what for is this change.

---


<!-- Sent from Reviewable.io -->

2021-03-02 18:55 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130#-:-MUoHq8s18NkjX2SQZ4l:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2021-03-03 08:50 UTC, igchor reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> just a small issue with the comment

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130#-:-MUrGx9J-DDech4PiweC:b-ms08na)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 563 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUrGfg6BBErmaXXAs7m:-MUrGfg6BBErmaXXAs7n:b-l2mf40) ([raw file](https://github.com/pmem/pmemkv-java/blob/9614d0db766fa3ce2147389e0545393d213b22f4/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L563)):*
> ```Java
> 	}
> 
> 	// JNI DATABASE METHODS
> ```

I don't think this comment is correct, the JNI methods are the one define below (private native). Could you move remove this comment?


<!-- Sent from Reviewable.io -->

2021-03-03 10:06 UTC, KFilipek reviewed
> Reviewed 2 of 3 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-03-03 10:11 UTC, igchor approved these changes
> Reviewed 2 of 3 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-03-03 10:38 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 574 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUreNq93L1gdKWqkL7Z:-MUreNq93L1gdKWqkL7_:b-xuoh06) ([raw file](https://github.com/pmem/pmemkv-java/blob/fcf5f9cada2fc41dc1c7f45c069fb915dba522be/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L574)):*
> ```Java
> 	private boolean stopped;
> 
> 	// JNI METHODS
> ```

no need to shorten the comment.
It should be `JNI DATABASE METHODS` - see above you have separate section "JNI DATABASE BUILDER METHODS"


<!-- Sent from Reviewable.io -->

2021-03-03 10:44 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[jni-binding/io_pmem_pmemkv_Database_Builder.cpp, line 20 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUrfqQ37v2KLsPxMIfX:-MUrfqQ37v2KLsPxMIfY:b-3l9h3k) ([raw file](https://github.com/pmem/pmemkv-java/blob/fcf5f9cada2fc41dc1c7f45c069fb915dba522be/jni-binding/io_pmem_pmemkv_Database_Builder.cpp#L20)):*
> ```cpp
> 
> extern "C" JNIEXPORT void JNICALL Java_io_pmem_pmemkv_Database_00024Builder_config_1delete
>   (JNIEnv *, jobject, jlong cfg) {
> ```

why did you change this?


<!-- Sent from Reviewable.io -->

2021-03-03 11:10 UTC, KFilipek reviewed
@igchor please merge it before Lukasz find another missing/additional space in this 3 line change xD

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130#-:-MUrlmhrB0J3Pcp9HbEf:b-wc556v)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_Builder.cpp, line 20 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUrfqQ37v2KLsPxMIfX:-MUrjG7t4ED6cQomGsSZ:b-5nw02d) ([raw file](https://github.com/pmem/pmemkv-java/blob/fcf5f9cada2fc41dc1c7f45c069fb915dba522be/jni-binding/io_pmem_pmemkv_Database_Builder.cpp#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why did you change this?
</blockquote></details>

The code below is correct declaration:
```
/*
 * Class:     io_pmem_pmemkv_Database_Builder
 * Method:    config_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pmem_pmemkv_Database_00024Builder_config_1delete
  (JNIEnv *, jobject, jlong);
```
The JNI method has definition that looks like:
```
private native void config_delete(long ptr);
```
Logically you should use **jlong**. 
Look above to the config_new, this function don't take any argument, but also has a **jobject** argument.
Also another methods below ignores **jobject** and use **jlong cfg**.
Helpful could be documentation for JNI mechanism in Java specification: [Here](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/design.html)
```c
jdouble Java_pkg_Cls_f__ILjava_lang_String_2 (
     JNIEnv *env,        /* interface pointer */
     jobject obj,        /* "this" pointer */
     jint i,             /* argument #1 */
     jstring s)          /* argument #2 */
{
     /* Obtain a C-copy of the Java string */
     const char *str = (*env)->GetStringUTFChars(env, s, 0);

     /* process the string */
     ...

     /* Now we are done with str */
     (*env)->ReleaseStringUTFChars(env, s, str);

     return ...
}
```
I think I explained it with details :)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 574 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUreNq93L1gdKWqkL7Z:-MUrlIrlDL56xqR-Mcd_:b-4uf610) ([raw file](https://github.com/pmem/pmemkv-java/blob/fcf5f9cada2fc41dc1c7f45c069fb915dba522be/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L574)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no need to shorten the comment.
It should be `JNI DATABASE METHODS` - see above you have separate section "JNI DATABASE BUILDER METHODS"

</blockquote></details>

fixed, especially for you :* 


<!-- Sent from Reviewable.io -->

2021-03-03 11:19 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130#-:-MUro8IQ91-81ztQ1a4c:bnfp4nl)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_Builder.cpp, line 20 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUrfqQ37v2KLsPxMIfX:-MUrnlOMElRs-o1ftnxu:bpu3uwy) ([raw file](https://github.com/pmem/pmemkv-java/blob/fcf5f9cada2fc41dc1c7f45c069fb915dba522be/jni-binding/io_pmem_pmemkv_Database_Builder.cpp#L20)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

The code below is correct declaration:
```
/*
 * Class:     io_pmem_pmemkv_Database_Builder
 * Method:    config_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pmem_pmemkv_Database_00024Builder_config_1delete
  (JNIEnv *, jobject, jlong);
```
The JNI method has definition that looks like:
```
private native void config_delete(long ptr);
```
Logically you should use **jlong**. 
Look above to the config_new, this function don't take any argument, but also has a **jobject** argument.
Also another methods below ignores **jobject** and use **jlong cfg**.
Helpful could be documentation for JNI mechanism in Java specification: [Here](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/design.html)
```c
jdouble Java_pkg_Cls_f__ILjava_lang_String_2 (
     JNIEnv *env,        /* interface pointer */
     jobject obj,        /* "this" pointer */
     jint i,             /* argument #1 */
     jstring s)          /* argument #2 */
{
     /* Obtain a C-copy of the Java string */
     const char *str = (*env)->GetStringUTFChars(env, s, 0);

     /* process the string */
     ...

     /* Now we are done with str */
     (*env)->ReleaseStringUTFChars(env, s, str);

     return ...
}
```
I think I explained it with details :)
</blockquote></details>

I see, so this means that we previously freed the `this` pointer 


<!-- Sent from Reviewable.io -->

2021-03-03 11:41 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/130)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_Builder.cpp, line 20 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/130#-MUrfqQ37v2KLsPxMIfX:-MUrt0mR172r9fMzEllI:b-tuik1l) ([raw file](https://github.com/pmem/pmemkv-java/blob/fcf5f9cada2fc41dc1c7f45c069fb915dba522be/jni-binding/io_pmem_pmemkv_Database_Builder.cpp#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I see, so this means that we previously freed the `this` pointer 
</blockquote></details>

Exactly


<!-- Sent from Reviewable.io -->

2021-03-03 11:47 UTC, merged