add caching direct buffer
pmem/pmemkv-java pull request #144
Opened 2021-03-23 13:27 UTC by JanDorniak99

2021-03-23 13:56 UTC, lukaszstolarczuk commented on pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java
> +						return ByteBuffer.allocateDirect(10000); // max size of key/value
are we going to make this limit some variable?
the default usage will change...?

2021-03-23 13:56 UTC, lukaszstolarczuk commented
@karczex, @igchor - what's the final decision - to stable branch (and make it 1.0.2) or to master (for 1.1 release)? I believe we can merge this into stable branch...

2021-03-25 12:48 UTC, igchor reviewed
As discussed today, to master.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144#-:-MWdQEXX6eNNwAvObNnF:by6zctu)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)



<!-- Sent from Reviewable.io -->

2021-03-25 13:22 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 2 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MWUGKwpzpIdZjQXZeFD-r1-42:-MWdSSv4E09VbyArxP0E:b-a9mtl2) ([raw file](https://github.com/pmem/pmemkv-java/blob/b24e742b9c2f2139f827b96367302d1b7e6c043b/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are we going to make this limit some variable?
the default usage will change...?
</blockquote></details>

As we discussed, this should be parametrized by builder method. 
Max size for allocateDirect() is int_max (~2Gb), which is pretty reasonable maximum for our buffer. 
Builder configuration  method  should throw IllegalArgumentException - If the capacity is a negative integer. 
10Mb by default probably OK.

And we needs tests for int max, and for negatives values
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 245 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MWdTofj7WKuGzK3bedN:-MWdTofj7WKuGzK3bedO:b-eyh0bj) ([raw file](https://github.com/pmem/pmemkv-java/blob/b24e742b9c2f2139f827b96367302d1b7e6c043b/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L245)):*
Let's give some meaning to this new parameter :)

> ```
> getDirectBuffer(keyConverter.toByteBuffer(key1), 0);
> ```
It would be more readable if this call looks like this:

```
getDirectBuffer(keyConverter.toByteBuffer(key1), ThreadDirectBuffers.KEY_BUFFER);
getDirectBuffer(keyConverter.toByteBuffer(key1), ThreadDirectBuffers.VALUE_BUFFER);
```

it may be implemented in ThreadDirexrBuffers class as 
```
 public static final int KEY_BUFFER = 1;
```


<!-- Sent from Reviewable.io -->

2021-04-01 09:12 UTC, lukaszstolarczuk reviewed
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBeqlCEs1mIFkD5ynt:-MXBeqlCEs1mIFkD5ynu:b-381bld) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
> ```Java
> 		private Converter<K> keyConverter;
> 		private Converter<V> valueConverter;
> 		private int keyBufferSize = 10000;
> ```

`size_t`
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, line 473 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBgA6R-nqrv8qpZ1Fa:-MXBgA6R-nqrv8qpZ1Fb:bmoo6sd) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java#L473)):*
> ```Java
> 
> 		ArrayList<Thread> threads = new ArrayList<>();
> 		for (int i = 0; i < 8; ++i) {
> ```

`8` and `100` should be const in this test
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, line 520 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBgoKdCEwmFg7R2Lf4:-MXBgoKdCEwmFg7R2Lf5:b6yem2d) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java#L520)):*
> ```Java
> 
> 	@Test
> 	public void usesNotDefaultCacheBuffersTest() {
> ```

\+ some test for MT accesses with non default cache buf sizes


<!-- Sent from Reviewable.io -->

2021-04-01 10:23 UTC, igchor requested changes
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 11 unresolved discussions (waiting on @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 53 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBv9JE3ldBVrC6eRSx:-MXBv9JE3ldBVrC6eRSy:bt5e12p) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L53)):*
> ```Java
> 	}
> 
> 	private ThreadLocal<ThreadDirectBuffers> directBuffers = new ThreadLocal<ThreadDirectBuffers>() {
> ```

Some comments would nice here (why we keep those buffers in tls).
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 88 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBvcE23mIGZtEoR-5E:-MXBvcE23mIGZtEoR-5F:b-kmezfg) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L88)):*
> ```Java
> 	}
> 
> 	private static <Key, Value> void valueCallbackWrapper(Database<Key, Value> db, ValueCallback<Value> callback, int s,
> ```

You could also add some comments here - describe this optimization.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBxHAqAJSpBBzqGRqN:-MXBxHAqAJSpBBzqGRqO:b-bhz5n1) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
> ```Java
> 		private Converter<K> keyConverter;
> 		private Converter<V> valueConverter;
> 		private int keyBufferSize = 10000;
> ```

Those values should probably be mentioned somewhere in the documentation.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 450 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBw9yJ1SjviQPVC-R5:-MXBw9yJ1SjviQPVC-R6:b-1erkhq) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L450)):*
> ```Java
> 		private int keyBufferSize = 10000;
> 		private int valueBufferSize = 10000;
> ```

I think we could make it bigger (at least for value). Even 1 or 10 MB (right now, its ~ 10KB I belive)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 570 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBwFtY48ZNquKT0lGo:-MXBwFtY48ZNquKT0lGp:b-ew996b) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L570)):*
> ```Java
> 		 */
> 		public Builder<K, V> setValueBufferSize(int size) {
> 			this.valueBufferSize = size;
> ```

probably we should have some check here (like Paweł mentioned, there is 2GB limit)
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, line 555 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBx9iR-IasmRuC0xOf:-MXBx9iR-IasmRuC0xOg:b9x0ycf) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java#L555)):*
> ```Java
> 
> 		db.stop();
> 	}
> ```

Maybe also some tests where we have multiple instances of Database?


<!-- Sent from Reviewable.io -->

2021-04-02 13:08 UTC, KFilipek reviewed
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 13 unresolved discussions (waiting on @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 97 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXHXJxT2zIXTejMCyVU:-MXHXJxT2zIXTejMCyVV:b-nysgm8) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/jni-binding/io_pmem_pmemkv_Database.cpp#L97)):*
> ```cpp
>         callback = callback_;
> 
>         if (mid_ == NULL) {
> ```

== nullptr or simply:
```cpp
if (mid_) {
    code
}
```
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 131 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXHXdIs0uhLxoGLl8QH:-MXHXdIs0uhLxoGLl8QI:bbbghzf) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/jni-binding/io_pmem_pmemkv_Database.cpp#L131)):*
> ```cpp
> 
> extern "C" JNIEXPORT void JNICALL Java_io_pmem_pmemkv_Database_database_1get_1keys_1buffer
>         (JNIEnv* env, jobject obj, jobject pointer, jobject callback) {
> ```

Are you sure that we pass here jobject instead of jlong?
Please generate headers for Java class and compare it, function below you have ```jlong pointer``` :)
Keep in mind that on newer JDK's javah went out and currently javac takes responsibility to generate JNI header files with -h option.
Look at this:
[JNI types and data structures](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 6 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXHZ6AZ8nojmHTKZZ7A:-MXHZ6A_CxzMr9MoBryR:bjzmcav) ([raw file](https://github.com/pmem/pmemkv-java/blob/aa6d209daf77926848ef3878a504083da6e350c7/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L6)):*
> ```Java
> package io.pmem.pmemkv;
> 
> import io.pmem.pmemkv.internal.*;
> ```

good catch, thanks!


<!-- Sent from Reviewable.io -->

2021-04-07 09:50 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 2 of 7 files reviewed, 13 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MWUGKwpzpIdZjQXZeFD-r1-42:-MXC9BTj0a8jMPnB1x7r:b-oiden5) ([raw file](https://github.com/pmem/pmemkv-java/blob/b24e742b9c2f2139f827b96367302d1b7e6c043b/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L42)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

As we discussed, this should be parametrized by builder method. 
Max size for allocateDirect() is int_max (~2Gb), which is pretty reasonable maximum for our buffer. 
Builder configuration  method  should throw IllegalArgumentException - If the capacity is a negative integer. 
10Mb by default probably OK.

And we needs tests for int max, and for negatives values

</blockquote></details>

I added the test for negative values. In the case of values bigger than int_max, we get a compilation error (integer number too large: 2147483648).
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBeqlCEs1mIFkD5ynt:-MXCBxPmEiFiIaQF4fdS:b-44n42o) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`size_t`
</blockquote></details>

Unfortunately java doesnt have equivalent for size_t (https://stackoverflow.com/questions/24747697/are-there-any-equivalents-to-size-t-in-c-in-java)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 450 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBw9yJ1SjviQPVC-R5:-MXC9kJL5c95MCtX-2Hj:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L450)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think we could make it bigger (at least for value). Even 1 or 10 MB (right now, its ~ 10KB I belive)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 570 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBwFtY48ZNquKT0lGo:-MXC1cAf7L5fc-fyuKC3:b-oiden5) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L570)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

probably we should have some check here (like Paweł mentioned, there is 2GB limit)
</blockquote></details>

I added the test for negative values. In the case of values bigger than int_max, we get a compilation error (integer number too large: 2147483648).
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, line 473 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBgA6R-nqrv8qpZ1Fa:-MXCAq-ZC-R9OLINgxjn:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java#L473)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`8` and `100` should be const in this test
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, line 520 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBgoKdCEwmFg7R2Lf4:-MXfiGnS4w0j55ymWi9Q:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java#L520)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ some test for MT accesses with non default cache buf sizes
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, line 555 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBx9iR-IasmRuC0xOf:-MXfiHYn2cyCP-0xhxqr:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java#L555)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Maybe also some tests where we have multiple instances of Database?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-07 11:12 UTC, KFilipek reviewed
> Reviewed 2 of 5 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 13 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-04-08 09:37 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 13 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 97 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXHXJxT2zIXTejMCyVU:-MXgXKDi2FQheCPZboJU:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/jni-binding/io_pmem_pmemkv_Database.cpp#L97)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

== nullptr or simply:
```cpp
if (mid_) {
    code
}
```
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 131 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXHXdIs0uhLxoGLl8QH:-MXfiMRm0h5H-ykI_lkU:bezhw2e) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/jni-binding/io_pmem_pmemkv_Database.cpp#L131)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Are you sure that we pass here jobject instead of jlong?
Please generate headers for Java class and compare it, function below you have ```jlong pointer``` :)
Keep in mind that on newer JDK's javah went out and currently javac takes responsibility to generate JNI header files with -h option.
Look at this:
[JNI types and data structures](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html)


</blockquote></details>

Yes there should be jlong, thanks :)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 53 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBv9JE3ldBVrC6eRSx:-MXkTZyT-tAp0WIIUoUW:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L53)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Some comments would nice here (why we keep those buffers in tls).
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 88 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBvcE23mIGZtEoR-5E:-MXkcamz7WBWKLvNfDDJ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L88)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You could also add some comments here - describe this optimization.
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBxHAqAJSpBBzqGRqN:-MXkk_qj49Vs-__gu1Gm:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Those values should probably be mentioned somewhere in the documentation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-09 13:35 UTC, lukaszstolarczuk reviewed
> Reviewed 3 of 5 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 6 of 7 files reviewed, 33 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBeqlCEs1mIFkD5ynt:-MXq_tvhDx1kTZ6zXty_:b-bhtl97) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Unfortunately java doesnt have equivalent for size_t (https://stackoverflow.com/questions/24747697/are-there-any-equivalents-to-size-t-in-c-in-java)
</blockquote></details>

hmm.. so maybe `long` then?
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 59 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqYDR97DZywkCeYDD3:-MXqYDRA7LZy_kc1Rzis:b-ce3dw3) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L59)):*
> ```Java
> 	 * allocate a new direct ByteBuffers (that is a very costly operation) in case
> 	 * of almost every operation. Sizes of this cached buffers can be set during
> 	 * creating DB (setKeyBufferSize(int) and setValueBufferSize(int)). Default both
> ```

`By default`
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 481 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqa22WD-iGMq8O1qk1:-MXqa22WD-iGMq8O1qk2:bo0qq34) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L481)):*
> ```Java
> 		private Converter<K> keyConverter;
> 		private Converter<V> valueConverter;
> 		private int keyBufferSize = 10000000; /* default size - 10MB */
> ```

hmm this is not exactly 10MB I guess - make it: 10 * 1024**2
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 599 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_Cb8645ulGNGwQe9:-MXq_Cb8645ulGNGwQeA:b3leod) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L599)):*
> ```Java
> 
> 		/**
> 		 * Sets a size of a preallocated direct buffers for keys (there are 2 buffers).
> ```

perhaps more precise: `(there are two buffers, per thread).`
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 600 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqZTIy6IvnAPjcWhTO:-MXqZTIy6IvnAPjcWhTP:b-vn2i6z) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L600)):*
> ```Java
> 		/**
> 		 * Sets a size of a preallocated direct buffers for keys (there are 2 buffers).
> 		 * This buffers allow avoiding further costly allocations. So the size should be
> ```

`These buffers`
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 601 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqZWrIESGGZwICYBKG:-MXqZWrIESGGZwICYBKH:b-370ayi) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L601)):*
> ```Java
> 		 * Sets a size of a preallocated direct buffers for keys (there are 2 buffers).
> 		 * This buffers allow avoiding further costly allocations. So the size should be
> 		 * bigger than most of the keys in the DB because in case of every bigger key
> ```

`than most of the (expected) keys` (?)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 601 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqZmwlD17Mb-rdPduc:-MXqZmwlD17Mb-rdPdud:b-3gzt9h) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L601)):*
> ```Java
> 		 * Sets a size of a preallocated direct buffers for keys (there are 2 buffers).
> 		 * This buffers allow avoiding further costly allocations. So the size should be
> 		 * bigger than most of the keys in the DB because in case of every bigger key
> ```

`in the DB**,** because`
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 602 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqZe0V-ke5k4pDZcOn:-MXqZe0V-ke5k4pDZcOo:b-asb43y) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L602)):*
> ```Java
> 		 * This buffers allow avoiding further costly allocations. So the size should be
> 		 * bigger than most of the keys in the DB because in case of every bigger key
> 		 * than size of the buffer there is required an additional allocation. Every
> ```

perhaps a bit simpler: `...than **the** size of the buffer, an additional allocation is required.`
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 607 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_jL84mLu4bdSg2oT:-MXq_jL84mLu4bdSg2oU:badhm1u) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L607)):*
> ```Java
> 		 *
> 		 * @param size
> 		 *            Size of a buffer.
> ```

`of a key buffer(s).`
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 607 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_xqkCvKTeDgOIGE0:-MXq_xqkCvKTeDgOIGE1:bvnv2eu) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L607)):*
> ```Java
> 		 *
> 		 * @param size
> 		 *            Size of a buffer.
> ```

this is in bytes?
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 612 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqpwtVCCuyGCRK3zpv:-MXqpwtVCCuyGCRK3zpw:b-km6w0v) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L612)):*
> ```Java
> 		 * @since 1.1
> 		 */
> 		public Builder<K, V> setKeyBufferSize(int size) {
> ```

\+ `throws` here and in the description (here and in the second method) 
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 623 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_TC_7ggcUJjJ0l8H:-MXq_TC_7ggcUJjJ0l8I:b-otsz) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L623)):*
> ```Java
> 		 * Sets a size of a preallocated direct buffer for values. This buffer allows
> 		 * avoiding further costly allocations. So the size should be bigger than most
> 		 * of values in the DB because in case of every bigger value than size of the
> ```

expected/estimated/.. values
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 623 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_XqlEKhc3vkrcbRk:-MXq_XqlEKhc3vkrcbRl:b-xz18ox) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L623)):*
> ```Java
> 		 * Sets a size of a preallocated direct buffer for values. This buffer allows
> 		 * avoiding further costly allocations. So the size should be bigger than most
> 		 * of values in the DB because in case of every bigger value than size of the
> ```

than the size of the buffer, and additional allocation is required.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 629 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/ [...]

2021-04-09 17:31 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 6 of 7 files reviewed, 32 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBeqlCEs1mIFkD5ynt:-MXrfWba96VorIz3iNuB:b-ikuphd) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. so maybe `long` then?
</blockquote></details>

If value suites to type and there is no calculations resulting in overload it doesn't matter
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 599 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_Cb8645ulGNGwQe9:-MXrfmVs0LtobiiHF3cB:bp5iy6x) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L599)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps more precise: `(there are two buffers, per thread).`
</blockquote></details>

Without ',' before "per thread"


<!-- Sent from Reviewable.io -->

2021-04-12 06:45 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 6 of 7 files reviewed, 32 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MWUGKwpzpIdZjQXZeFD-r1-42:-MY3oPyN8QAM3buYkAvY:b-mwkp3f) ([raw file](https://github.com/pmem/pmemkv-java/blob/b24e742b9c2f2139f827b96367302d1b7e6c043b/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L42)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

I added the test for negative values. In the case of values bigger than int_max, we get a compilation error (integer number too large: 2147483648).
</blockquote></details>

we should also add test for max int/long type
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBeqlCEs1mIFkD5ynt:-MY3nyTQ9GSy8L6Sw2ch:b-vx5wzm) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

If value suites to type and there is no calculations resulting in overload it doesn't matter
</blockquote></details>

it matters, because it holds size (given by user), so bigger is better in this case...? ;)


<!-- Sent from Reviewable.io -->

2021-04-12 09:09 UTC, KFilipek reviewed
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 31 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBeqlCEs1mIFkD5ynt:-MY4KLip-HPzZnqNoBmS:bfncv65) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
> ```
> keyBufferSize
> ```
I see, +1


<!-- Sent from Reviewable.io -->

2021-04-13 07:30 UTC, karczex commented
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 85 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MY97eZe9FYLzZCbnc2q:-MY97eZf0v2GTN-1xNeo:b4cv65y) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L85)):*
> ```Java
> 
> 	private ByteBuffer getDirectKeyBuffer(ByteBuffer buf, int number) {
> 		assert number == ThreadDirectBuffers.KEY1_BUFFER || number == ThreadDirectBuffers.KEY2_BUFFER;
> ```

Please, make sure, the assertions are enabled in pom file


<!-- Sent from Reviewable.io -->

2021-04-13 07:35 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 31 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBeqlCEs1mIFkD5ynt:-MY98c3xD1xLjxV5LBty:bwpees1) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> keyBufferSize
> ```
I see, +1
</blockquote></details>

Direct buffer may be size int_max anyway, so int is rather OK.


<!-- Sent from Reviewable.io -->

2021-04-13 08:28 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 31 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MWUGKwpzpIdZjQXZeFD-r1-42:-MY4JpWI2AqpaeN3z4Ci:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b24e742b9c2f2139f827b96367302d1b7e6c043b/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we should also add test for max int/long type
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBeqlCEs1mIFkD5ynt:-MY47LKA4VcuNEcgJ2tv:bhcq7rs) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Direct buffer may be size int_max anyway, so int is rather OK.
</blockquote></details>

Yes, we pass int to allocateDirect method, so anyway long would be cast to int.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 59 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqYDR97DZywkCeYDD3:-MY3wand0ce_ePsbyjD8:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`By default`
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 85 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MY97eZe9FYLzZCbnc2q:-MY9KFka-ce-Mw3RSBBY:b-r2ujxd) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L85)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Please, make sure, the assertions are enabled in pom file
</blockquote></details>

They are enabled in tests by default. In other cases they have to be enabled during executing java (-ea flag) (https://stackoverflow.com/questions/19966620/enable-assert-in-a-maven-built-project)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 481 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqa22WD-iGMq8O1qk1:-MY3wx_1AbmpSjF3WneC:bawz4u5) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L481)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm this is not exactly 10MB I guess - make it: 10 * 1024**2
</blockquote></details>

10 * 1024**2 - isnt that 10 MiB?
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 599 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_Cb8645ulGNGwQe9:-MY3xKBg87vj_50FugyN:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L599)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Without ',' before "per thread"
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 600 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqZTIy6IvnAPjcWhTO:-MY3xOizCKr-q5aYs4KQ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L600)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`These buffers`
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 601 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqZWrIESGGZwICYBKG:-MY3xgMH8043GfsKfAEa:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L601)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`than most of the (expected) keys` (?)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 601 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqZmwlD17Mb-rdPduc:-MY3xh2E0P5FFCBhuqaq:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L601)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`in the DB**,** because`
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 602 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqZe0V-ke5k4pDZcOn:-MY4-oin3RDCtYPAUgii:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L602)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps a bit simpler: `...than **the** size of the buffer, an additional allocation is required.`
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 607 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_jL84mLu4bdSg2oT:-MY4-uZKCC3cCsjv6lEu:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L607)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`of a key buffer(s).`
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 607 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_xqkCvKTeDgOIGE0:-MY4-utw-4ZaxwO3A_6V:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L607)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this is in bytes?
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 612 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqpwtVCCuyGCRK3zpv:-MY450r1BkURoJBgQIOZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L612)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ `throws` here and in the description (here and in the second method) 
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 623 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_TC_7ggcUJjJ0l8H:-MY47ByD8d577bjDnRHG:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L623)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

expected/estimated/.. values
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 623 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXq_XqlEKhc3vkrcbRk:-MY411w96U0ISRJnFkWZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3e [...]

2021-04-13 10:35 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 3 of 7 files reviewed, 14 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 448 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXBeqlCEs1mIFkD5ynt:-MY9bXkX6fKO1AieGKy4:b-lwx50o) ([raw file](https://github.com/pmem/pmemkv-java/blob/8042e829ada95805dfb3350701e63c4bdd21b037/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L448)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Yes, we pass int to allocateDirect method, so anyway long would be cast to int.
</blockquote></details>

then pls put it somewhere (in docs) as a limitation
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 481 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqa22WD-iGMq8O1qk1:-MY9asO8-_C3-wIYzhNO:b-itmovw) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L481)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

10 * 1024**2 - isnt that 10 MiB?
</blockquote></details>

yeah, but we like mebibytes ;)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 612 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqpwtVCCuyGCRK3zpv:-MY9mpbC4Eg5U-T8XTA7:b-qa2oqu) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L612)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the method itself should also say "throws", I guess


<!-- Sent from Reviewable.io -->

2021-04-13 11:22 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 3 of 7 files reviewed, 13 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 481 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqa22WD-iGMq8O1qk1:-MY9r72-EbsueZAtiXV7:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L481)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

yeah, but we like mebibytes ;)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-13 15:03 UTC, lukaszstolarczuk reviewed
> Reviewed 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 134 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqorMz4MMtVR_e82JH:-MYAcZtZABjycvCBivF0:b-v2ty3x) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L134)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done, now (after recent changes) num of elems is < 100
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 91 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYAbNX55BqpvxTC_KQP:-MYAbNX6B5_r9pIICDyq:bv79bht) ([raw file](https://github.com/pmem/pmemkv-java/blob/327518b6ecd6663ad239a8df040ca9bc8f48f584/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L91)):*
> ```Java
> 	}
> 
> 	/* Test using multiple instances of the one DB */
> ```

`of the same DB` sounds better
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java, line 41 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqfqbkB8CunTiSXcW7:-MYAk6MUBh5jz6_Ip_VV:b-ucfknh) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java#L41)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2021-04-14 08:13 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 134 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqorMz4MMtVR_e82JH:-MYERBnjBigzeRIJhMam:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L134)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done, now (after recent changes) num of elems is < 100
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 91 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYAbNX55BqpvxTC_KQP:-MYERBC3CZLgZ0eGbJDi:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/327518b6ecd6663ad239a8df040ca9bc8f48f584/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`of the same DB` sounds better
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-14 08:51 UTC, igchor requested changes
> Reviewed 2 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 97 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYEZLzr7A1QgR8OOFYT:-MYEZLzr7A1QgR8OOFYU:bhu0gqy) ([raw file](https://github.com/pmem/pmemkv-java/blob/84850fe6bc5934fd9334d999ab0f49da2d738d61/jni-binding/io_pmem_pmemkv_Database.cpp#L97)):*
> ```cpp
>         callback = callback_;
> 
>         if (!mid_) {
> ```

Hm, can there be a race condition on this assignment? It's possible that 2 threads will execute this code at the same time, right?

Maybe instead of lazy initialization we should use a dedicated method after all, which would be called in Database constructor.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 102 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYEXOcm2e2EY4Ix8Ce5:-MYEXOcm2e2EY4Ix8Ce6:b-rrzp9r) ([raw file](https://github.com/pmem/pmemkv-java/blob/84850fe6bc5934fd9334d999ab0f49da2d738d61/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L102)):*
> ```Java
> 
> 		runParallel(threadsNumber, () -> {
> 			Database<ByteBuffer, ByteBuffer> threadDB = openDB(ENGINE, file, new ByteBufferConverter());
> ```

Hm, this is not a valid use I think. If you want to access specific database you must use the same db instance. What I meant by testing multiple instances is to have something like this multipleDBTypesTest


<!-- Sent from Reviewable.io -->

2021-04-14 10:51 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 97 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYEZLzr7A1QgR8OOFYT:-MYEzSu9D4aFwPCqBxTD:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/84850fe6bc5934fd9334d999ab0f49da2d738d61/jni-binding/io_pmem_pmemkv_Database.cpp#L97)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, can there be a race condition on this assignment? It's possible that 2 threads will execute this code at the same time, right?

Maybe instead of lazy initialization we should use a dedicated method after all, which would be called in Database constructor.
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 102 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYEXOcm2e2EY4Ix8Ce5:-MYEzVApDZwWstTQUpsH:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/84850fe6bc5934fd9334d999ab0f49da2d738d61/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L102)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, this is not a valid use I think. If you want to access specific database you must use the same db instance. What I meant by testing multiple instances is to have something like this multipleDBTypesTest
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-15 07:29 UTC, igchor requested changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 103 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYJQcGA8JfzF66z_psq:-MYJQcGBDQuCko-oDji9:b-foofyb) ([raw file](https://github.com/pmem/pmemkv-java/blob/68a7fb37959ed5159e562ddc5c25017f2b50cb08/jni-binding/io_pmem_pmemkv_Database.cpp#L103)):*
> ```cpp
>     jmethodID mid;
> 
>     Context(JNIEnv* env_, jobject db_, jobject callback_, jmethodID &mid_) {
> ```

can we drop the reference now? (just pass by value)


<!-- Sent from Reviewable.io -->

2021-04-15 07:34 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 103 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYJQcGA8JfzF66z_psq:-MYJS0Sf0ka7rlGmYDAr:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/68a7fb37959ed5159e562ddc5c25017f2b50cb08/jni-binding/io_pmem_pmemkv_Database.cpp#L103)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

can we drop the reference now? (just pass by value)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-15 12:13 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144#-:-MYKRn-S9FrwpjsdSlVY:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-04-15 14:11 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: all files reviewed, 4 unresolved discussions (waiting on @JanDorniak99 and @karczex)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 134 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqorMz4MMtVR_e82JH:-MYKrQ2ZCSKxw4XHpO6u:bpobej) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L134)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

hmm.. still not done?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 91 at r8](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYKrbrO279rJGHmBVP6:-MYKrbrO279rJGHmBVP7:b-qzqy1w) ([raw file](https://github.com/pmem/pmemkv-java/blob/69d8987b387ad1240f548d05f6ce2f873adcafb2/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L91)):*
> ```Java
> 	}
> 
> 	/* Test the DB on the multiple threads */
> ```

`on multiple threads` is enough (drop `the`)
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 127 at r8](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYKrmIl9TxXzrjz703J:-MYKrmIl9TxXzrjz703K:b-mg4ui2) ([raw file](https://github.com/pmem/pmemkv-java/blob/69d8987b387ad1240f548d05f6ce2f873adcafb2/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L127)):*
> ```Java
> 	}
> 
> 	/* Test using multiple instances of 2 different DBs */
> ```

pls fix this comment


<!-- Sent from Reviewable.io -->

2021-04-16 09:19 UTC, KFilipek reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r5, 1 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144#-:-MYOySOC62zkiMcpplwe:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @JanDorniak99 and @karczex)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java, line 71 at r8](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYOyEBaEv6d0eOS32hN:-MYOyEBbAiurP_9yRiq3:b-a51imz) ([raw file](https://github.com/pmem/pmemkv-java/blob/69d8987b387ad1240f548d05f6ce2f873adcafb2/pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java#L71)):*
> ```Java
> 	public static <KV> Database<KV, KV> createDB(String engine, String path, Converter<KV> kvConverter) {
> 		return new Database.Builder<KV, KV>(engine)
> 				.setSize(1073741824)
> ```

I believe we can hold size separately to not duplicate, despite this it looks good


<!-- Sent from Reviewable.io -->

2021-04-19 08:37 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 134 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqorMz4MMtVR_e82JH:-MYdFCZ21iyLsdtsQvgF:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L134)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. still not done?
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 91 at r8](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYKrbrO279rJGHmBVP6:-MYdDd0rBihF3Q5GCJQm:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/69d8987b387ad1240f548d05f6ce2f873adcafb2/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`on multiple threads` is enough (drop `the`)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 127 at r8](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYKrmIl9TxXzrjz703J:-MYdEUo36hLvF896Pbsx:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/69d8987b387ad1240f548d05f6ce2f873adcafb2/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L127)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls fix this comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-20 07:33 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @igchor, @JanDorniak99, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 60 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYiB8UC6Ow3641ofj06:-MYiB8UC6Ow3641ofj07:bddg5ud) ([raw file](https://github.com/pmem/pmemkv-java/blob/02c51e80a136d4bc11c486165cc57ee7238676ff/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L60)):*
> ```Java
> 	 * of almost every operation. Sizes of this cached buffers can be set during
> 	 * creating DB (setKeyBufferSize(int) and setValueBufferSize(int)). By default
> 	 * both sizes are equal to 10MiB.
> ```

I believe you can remove the default size information from here (it won't be updated, most likely, if we change the default). It's duplicated from Builder methods and actually I'm not sure it's relevant here.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 481 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYiA2YF-q-YO_NetAU9:-MYiA2YGCw-NVwR9VXZ7:b-cpmin2) ([raw file](https://github.com/pmem/pmemkv-java/blob/02c51e80a136d4bc11c486165cc57ee7238676ff/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L481)):*
> ```Java
> 		private Converter<K> keyConverter;
> 		private Converter<V> valueConverter;
> 		private int keyBufferSize = 1048576; /* default size - 10MiB */
> ```

wait.. it's not 10 Megs it's 1KiB...?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 134 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MXqorMz4MMtVR_e82JH:-MYiAfOZ-Ay5k7P1esDY:b-odzzml) ([raw file](https://github.com/pmem/pmemkv-java/blob/1eff91af3ecafbf013f91fb3708e7ecc6fe44c54/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L134)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

hmm right now only 1 element (in the second DB) will require the extra buffer, the other elements will fit in the specified buffer size, aren't they? perhaps make the second's DB buffer sizes like `180` just instead of `200`...?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java, line 17 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYiAQvw1KKH-yrQC5kk:-MYiAQvw1KKH-yrQC5kl:bxpvdo8) ([raw file](https://github.com/pmem/pmemkv-java/blob/02c51e80a136d4bc11c486165cc57ee7238676ff/pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java#L17)):*
> ```Java
> 
> class TestUtils {
> 	private static final long DEFAULT_DB_SIZE = 1073741824;
> ```

test DB size is only 1MiB ? I know it works, but it just seems low


<!-- Sent from Reviewable.io -->

2021-04-20 08:01 UTC, JanDorniak99 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 60 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYiB8UC6Ow3641ofj06:-MYiCsyH453rUE34sP3l:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/02c51e80a136d4bc11c486165cc57ee7238676ff/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L60)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you can remove the default size information from here (it won't be updated, most likely, if we change the default). It's duplicated from Builder methods and actually I'm not sure it's relevant here.
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 481 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYiA2YF-q-YO_NetAU9:-MYiDCat4UPltX588VvH:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/02c51e80a136d4bc11c486165cc57ee7238676ff/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L481)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

wait.. it's not 10 Megs it's 1KiB...?
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java, line 17 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYiAQvw1KKH-yrQC5kk:-MYiE25i8BzohqhRpvEy:belpbhn) ([raw file](https://github.com/pmem/pmemkv-java/blob/02c51e80a136d4bc11c486165cc57ee7238676ff/pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

test DB size is only 1MiB ? I know it works, but it just seems low
</blockquote></details>

It's 1024 MiB


<!-- Sent from Reviewable.io -->

2021-04-20 10:46 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, 1 of 2 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/144#-:-MYismmB8bcor4rBvKmo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java, line 17 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/144#-MYiAQvw1KKH-yrQC5kk:-MYipip92fgDAvoSaYkg:b7fsfr8) ([raw file](https://github.com/pmem/pmemkv-java/blob/02c51e80a136d4bc11c486165cc57ee7238676ff/pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java#L17)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

It's 1024 MiB
</blockquote></details>

yeah, ok, I panicked :D


<!-- Sent from Reviewable.io -->

2021-04-22 07:48 UTC, merged