Java: Iterator API implementation
pmem/pmemkv-java pull request #145
Opened 2021-04-14 08:58 UTC by KFilipek

2021-05-19 07:18 UTC, igchor reviewed
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @KFilipek)

___
*[.github/workflows/gha.yml, line 31 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Ma2S8qN-Jj6P1CCiejV:-Ma2S8qN-Jj6P1CCiejW:b-ihsib) ([raw file](https://github.com/pmem/pmemkv-java/blob/f553fa045a14ea0d40988564072c74b78e93821a/.github/workflows/gha.yml#L31)):*
> ```YAML
>       matrix:
>         CONFIG: ["OS=ubuntu OS_VER=20.04 PMEMKV=master PUSH_IMAGE=1",
>           #"OS=ubuntu OS_VER=20.04 PMEMKV=stable-1.0",
> ```

you can just remove all those configurations
___
*[jni-binding/common.h, line 49 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Ma2TRIcATT0LhDXgU_W:-Ma2TRIcATT0LhDXgU_X:b-v7zgxo) ([raw file](https://github.com/pmem/pmemkv-java/blob/f553fa045a14ea0d40988564072c74b78e93821a/jni-binding/common.h#L49)):*
> ```objc
> };
> 
> #define KEY_CALLBACK_NAME "keyCallbackWrapper"
> ```

Do you need those defines here? They can probably stay in Database.cpp and then you could name this file as exception_Handling.h or something similar.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Ma2T4kV-n4D2m6WfKWq:-Ma2T4kV-n4D2m6WfKWr:b-fwl5qy) ([raw file](https://github.com/pmem/pmemkv-java/blob/f553fa045a14ea0d40988564072c74b78e93821a/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L34)):*
> ```cpp
>   else
>   {
>     if (res.get_status() != pmem::kv::status::OK)
> ```

this is always true
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Ma2TkdOBR45PakCHWiz:-Ma2TkdOBR45PakCHWj-:b-86qdi3) ([raw file](https://github.com/pmem/pmemkv-java/blob/f553fa045a14ea0d40988564072c74b78e93821a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L42)):*
> ```Java
> 			System.out.println(it_ptr);
> 		}
> 		public void seek(String key) {
> ```

K key
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 45 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Ma2TzZN7OwiS__kDoxN:-Ma2TzZN7OwiS__kDoxO:b-3f1qyj) ([raw file](https://github.com/pmem/pmemkv-java/blob/f553fa045a14ea0d40988564072c74b78e93821a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L45)):*
> ```Java
> 			// iterator_seek(it_ptr, key);
> 		}
> 		public void seek_to_first() {
> ```

Probably seekToFirst to make it consistent with other methods.


<!-- Sent from Reviewable.io -->

2021-05-26 10:09 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: 4 of 9 files reviewed, 11 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 94 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac6g19-pFVwPY8WxkL:-Mac6g19-pFVwPY8WxkM:bpopk9) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L94)):*
> ```cpp
>   (JNIEnv *env, jobject, jlong ptr) {
>     auto w_it = reinterpret_cast<pmem::kv::db::write_iterator*>(ptr);
>     w_it->seek_to_first();
> ```

you should probably handle error here (status).
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 113 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac7yMt47-NBNADw9PO:-Mac7yMt47-NBNADw9PP:bal5j9g) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L113)):*
> ```cpp
>   (JNIEnv *, jobject, jlong ptr) {
>     auto w_it = reinterpret_cast<pmem::kv::db::write_iterator*>(ptr);
>     return w_it->is_next() == pmem::kv::status::OK;
> ```

what if status is different than OK and NOT_FOUND - you should add some error handling
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 124 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac82PNAhI0WAMQ5aTm:-Mac82PNAhI0WAMQ5aTn:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L124)):*
> ```cpp
>   (JNIEnv *, jobject, jlong ptr) {
>     auto w_it = reinterpret_cast<pmem::kv::db::write_iterator*>(ptr);
>     return w_it->next() == pmem::kv::status::OK;
> ```

.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 148 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac84JkDyXx8lcPvxnt:-Mac84JkDyXx8lcPvxnu:bprdgga) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L148)):*
> ```cpp
>     auto key_size = key_value.size();
>     jbyteArray key_ba = env->NewByteArray(key_size);
>     env->SetByteArrayRegion(key_ba, 0, key_size, (const jbyte*)(key_value.data()));
> ```

This will make a copy, I think we don't want that - you should return ByteBuffer instead of byte array from this function. Similarly as we pass ByteBuffer to callback in Callback_get_value_buffer in line 117 line in Database.cpp
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 11 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac6NO7E8eFNesYRtK-:-Mac6NO7E8eFNesYRtK0:b3kre) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L11)):*
> ```Java
> import java.util.ArrayList;
> 
> import javax.swing.text.StyledEditorKit.BoldAction;
> ```

?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 3 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac8SDs4Qd8dMitCFa3:-Mac8SDs4Qd8dMitCFa4:blfo6ba) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L3)):*
> ```Java
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021, Intel Corporation */
> ```

Probably some tests for error handling would be nice


<!-- Sent from Reviewable.io -->

2021-05-26 10:29 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: 4 of 9 files reviewed, 11 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 3 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac8SDs4Qd8dMitCFa3:-MacD0qfCqCRljH7-gPH:b-593sd9) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L3)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Probably some tests for error handling would be nice
</blockquote></details>

I added a separate task for tests - for this PR we can just have a basic one like this.


<!-- Sent from Reviewable.io -->

2021-05-26 12:25 UTC, KFilipek reviewed
> Reviewed 1 of 9 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: 7 of 9 files reviewed, 11 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[.github/workflows/gha.yml, line 31 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Ma2S8qN-Jj6P1CCiejV:-MaccomuAhpO26ZU_BP3:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/f553fa045a14ea0d40988564072c74b78e93821a/.github/workflows/gha.yml#L31)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you can just remove all those configurations
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Ma2T4kV-n4D2m6WfKWq:-MacYajG-ylDIoKPv-Yv:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/f553fa045a14ea0d40988564072c74b78e93821a/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L34)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this is always true
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 94 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac6g19-pFVwPY8WxkL:-Mac_Mg46nDwTs-LuciI:b7l8e43) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L94)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you should probably handle error here (status).
</blockquote></details>

Done.
Also I've changed returned type, because in documentation status returned is OK or NOT_FOUND.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 113 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac7yMt47-NBNADw9PO:-Mac_Qkg62zHSiNkwwWb:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L113)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what if status is different than OK and NOT_FOUND - you should add some error handling
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 124 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac82PNAhI0WAMQ5aTm:-Mac_RZKBx_6nk_djiE1:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L124)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Ma2TkdOBR45PakCHWiz:-Mac_qjH1RoPeVuYFw8F:biismqc) ([raw file](https://github.com/pmem/pmemkv-java/blob/f553fa045a14ea0d40988564072c74b78e93821a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L42)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

K key
</blockquote></details>

Removed, it will be added as separate change
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 45 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Ma2TzZN7OwiS__kDoxN:-Mac_vxH1__pNW0OEHwB:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/f553fa045a14ea0d40988564072c74b78e93821a/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L45)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Probably seekToFirst to make it consistent with other methods.
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 11 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac6NO7E8eFNesYRtK-:-Mac_gCt7zxGzWEgfMXc:b-ltp2le) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

?
</blockquote></details>

I don't know what is it xD
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 3 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac8SDs4Qd8dMitCFa3:-MaccYMK3SYG_0gcp6IE:bdavwbt) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L3)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I added a separate task for tests - for this PR we can just have a basic one like this.
</blockquote></details>

Done.
Thanks, I will do that.


<!-- Sent from Reviewable.io -->

2021-05-26 13:08 UTC, igchor reviewed
> Reviewed 1 of 4 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @KFilipek)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 147 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Macm33m2fdG8wK8YRw3:-Macm33m2fdG8wK8YRw4:b-dpdr5v) ([raw file](https://github.com/pmem/pmemkv-java/blob/b39a8eb987270d4740efba45f22fb276849861b5/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L147)):*
> ```cpp
>     env->SetByteArrayRegion(key_ba, 0, key_size, (const jbyte*)(key_value.data()));
>     return key_ba;
>   }
> ```

error handling?


<!-- Sent from Reviewable.io -->

2021-05-26 14:50 UTC, KFilipek reviewed
> Reviewed 3 of 9 files at r1, 1 of 4 files at r2, 2 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[jni-binding/common.h, line 49 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Ma2TRIcATT0LhDXgU_W:-Mad8Nym5E2SsDT1iX5D:b-p4kyqm) ([raw file](https://github.com/pmem/pmemkv-java/blob/f553fa045a14ea0d40988564072c74b78e93821a/jni-binding/common.h#L49)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Do you need those defines here? They can probably stay in Database.cpp and then you could name this file as exception_Handling.h or something similar.
</blockquote></details>

Done, but with one exception, I didn't change the filename, because in the future probably we will move Janek's modification into this file and then it will handle more than handling.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 148 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac84JkDyXx8lcPvxnt:-Mad7tErBp1OfUyrV4dO:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L148)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This will make a copy, I think we don't want that - you should return ByteBuffer instead of byte array from this function. Similarly as we pass ByteBuffer to callback in Callback_get_value_buffer in line 117 line in Database.cpp
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 147 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Macm33m2fdG8wK8YRw3:-Mad7sriEMh5x_Ysgz4v:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b39a8eb987270d4740efba45f22fb276849861b5/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L147)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

error handling?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-27 12:55 UTC, igchor requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek)

___
*[jni-binding/common.h, line 11 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-MahqJzo4PL5kbX8u49f:-MahqJzo4PL5kbX8u49g:b-tuahz5) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/common.h#L11)):*
> ```objc
> #include <unordered_map>
> 
> #define DO_LOG 0
> ```

Hm, we don't use this anywhere, right? Can you remove this?
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 124 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mac82PNAhI0WAMQ5aTm:-MahriCk7F8xhTwmNphP:b1s2j3g) ([raw file](https://github.com/pmem/pmemkv-java/blob/537df552972d10f6b5a3569fb0878077a6432ece/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L124)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still don't see any error handling.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 147 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Macm33m2fdG8wK8YRw3:-Mahs6Bi2UpbIO_4f51O:bfz13l1) ([raw file](https://github.com/pmem/pmemkv-java/blob/b39a8eb987270d4740efba45f22fb276849861b5/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L147)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What if NewDirectByteBuffer fails?
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 29 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mahqloh4WBAMZyjVOEf:-Mahqloh4WBAMZyjVOEg:b-bd08p8) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L29)):*
> ```cpp
>     PmemkvJavaException(env).ThrowException(res.get_status());
>   }
>   return -1;
> ```

since this is treated as pointer, shouldn't you return 0 (NULL)? Also either move this return to else or remove the else branch entirely (it's not really necessary since the first branch has returned).
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 52 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-MahspKR0rvHECRwwdmh:-MahspKR0rvHECRwwdmi:b-bdishw) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L52)):*
> ```Java
> 		assertTrue(db.exists(stringToByteBuffer("key1")));
> 		Database<ByteBuffer, ByteBuffer>.WriteIterator it = db.iterator();
> 		it.seekToFirst();
> ```

assert(it.seekToFirst() == true)?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 75 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-MahsxKl5fY-wQondWBG:-MahsxKl5fY-wQondWBH:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L75)):*
> ```Java
> 
> 		Database<ByteBuffer, ByteBuffer>.WriteIterator it = db.iterator();
> 		it.seekToFirst();
> ```

.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 80 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Maht-qADCiI8g0lKM7S:-Maht-qADCiI8g0lKM7T:b-6egr50) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L80)):*
> ```Java
> 		while (it.isNext()) {
> 			counter++;
> 			it.next();
> ```

assert true?


<!-- Sent from Reviewable.io -->

2021-05-27 14:02 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 9 files at r1, 1 of 4 files at r2, 2 of 4 files at r3, 1 of 2 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: all files reviewed, 19 unresolved discussions (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mahvn_NA1sZe0d34yTI:-Mahvn_OBUzZ0QuBG3aQ:b-7ywgw7) (no related file):*
> Temporary off building with pmemkv-1.3 or less
in a commit msg - you're missing a verb - e.g. `Temporar**ily** turn off ...` 

---
___
*[jni-binding/common.h, line 11 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-MahqJzo4PL5kbX8u49f:-Mai7HNn7bF43ehqa0eh:b6mq9nu) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/common.h#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, we don't use this anywhere, right? Can you remove this?
</blockquote></details>

maybe not in this PR...? ;)
___
*[jni-binding/common.cpp, line 1 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-MahwxV3DfPYgI1cKcju:-MahwxV44-yLNJPTzG-d:b-nsqcu9) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/common.cpp#L1)):*
> ```cpp
> 
> ```

redundant empty line
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 8 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mahx-0A9-4-tLe6HqTr:-Mahx-0A9-4-tLe6HqTs:b-lajoya) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database.cpp#L8)):*
> ```cpp
> #include <string>
> #include <jni.h>
> #include <libpmemkv.hpp>
> ```

since you're including common.h you don't need this two includes
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 7 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mahx9pJ17MFaL7x543Z:-Mahx9pJ17MFaL7x543_:bqjxy4v) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L7)):*
> ```cpp
> #include <common.h>
> #include <jni.h>
> #include <libpmemkv.hpp>
> ```

 same here
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 14 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai4I3hEycy29-iuKTd:-Mai4I3hEycy29-iuKTe:bgdyy7s) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L14)):*
> ```cpp
> /*
>  * Class:     io_pmem_pmemkv_Database_WriteIterator
>  * Method:    iterator_new_write_iterator
> ```

do we have to repeat the word `iterator` in this name? in C API we call this `pmemkv_write_iterator_new` so maybe something like this...?
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 17 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai3grZ1RqMYGrz63cM:-Mai3gr_EX_PgnE28KqI:bmlxejf) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L17)):*
> ```cpp
>  * Signature: (J)J
>  */
> JNIEXPORT jlong JNICALL Java_io_pmem_pmemkv_Database_00024WriteIterator_iterator_1new_1write_1iterator(JNIEnv *env, jobject, jlong db_pointer)
> ```

quite a long line, can you pls break it..?
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 121 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai67rkCGZM_TXIHj9x:-Mai67rkCGZM_TXIHj9y:b4xmup5) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L121)):*
> ```cpp
>   (JNIEnv *, jobject, jlong ptr) {
>     auto w_it = reinterpret_cast<pmem::kv::db::write_iterator*>(ptr);
>     return w_it->next() == pmem::kv::status::OK;
> ```

in C++ `next` can also return NOT_FOUND
and what about possible other exceptions...?
___
*[jni-binding/libpmemkv_jni.map, line 2 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-MahxIMV787TnXDrNJdh:-MahxIMV787TnXDrNJdi:b-8mxykb) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/libpmemkv_jni.map#L2)):*
> ```
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020, Intel Corporation
> ```

-2021
___
*[jni-binding/libpmemkv_jni.map, line 36 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai2OxN7yUWCBaTM7XJ:-Mai2OxN7yUWCBaTM7XK:b-7rmul3) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/libpmemkv_jni.map#L36)):*
> ```
> 		Java_io_pmem_pmemkv_Database_00024WriteIterator_iterator_1key;
> 		Java_io_pmem_pmemkv_Database_00024WriteIterator_iterator_1next;
> 		Java_io_pmem_pmemkv_Database_00024WriteIterator_iterator_1is_1next;
> ```

I know they are not implemented yet, but there are already more new methods in the public API
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 38 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai-E-j8ezLPNqDKDTu:-Mai-E-j8ezLPNqDKDTv:bmpfyla) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L38)):*
> ```Java
> 
> 	public class WriteIterator {
> 		public WriteIterator(long database_handle) {
> ```

hm... I guess, we're also missing descriptions for all public WriteIterator methods/ctors (pls mark as you did for the `iterator` member)

and as Igor mentioned, I believe, it should be marked that this is an still experimental feature
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 200 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai-xYs5Yd-_LddnYQm:-Mai-xYs5Yd-_LddnYQn:b-aid891) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L200)):*
> ```Java
> 	 * TODO(kfilipek): fill description
> 	 *
> 	 * @throws DatabaseException
> ```

you didn't mark the code it can throw (next to the class definition, I guess )
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 39 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-MahzZ3x6boYg4Qi3VAW:-MahzZ3x6boYg4Qi3VAX:b-1o6o7j) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L39)):*
> ```Java
> 
> 	@After
> 	public void finish() {
> ```

do we need this empty method?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 46 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai1LyU93dF_mE3wHL4:-Mai1LyU93dF_mE3wHL5:bokbvpw) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L46)):*
> ```Java
> 		Database<ByteBuffer, ByteBuffer> db = buildDB(ENGINE);
> 		assertNotNull(db);
> 		assertFalse(db.stopped());
> ```

we can move these two lines into the helper `buildDB` method
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 51 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai1-q08pnA4wB_p-Op:-Mai1-q1EzjiHqKbu7-0:b-q8zq9k) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L51)):*
> ```Java
> 		db.put(stringToByteBuffer("key1"), stringToByteBuffer("value1"));
> 		assertTrue(db.exists(stringToByteBuffer("key1")));
> 		Database<ByteBuffer, ByteBuffer>.WriteIterator it = db.iterator();
> ```

we should also make sure `it` is not null, right..?


<!-- Sent from Reviewable.io -->

2021-05-27 17:14 UTC, KFilipek reviewed
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: 3 of 9 files reviewed, 19 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mahvn_NA1sZe0d34yTI:-MainiDBEP08aWPxf4NY:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> Temporary off building with pmemkv-1.3 or less
in a commit msg - you're missing a verb - e.g. `Temporar**ily** turn off ...` 
</blockquote></details>

Done.

---
___
*[jni-binding/common.h, line 11 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-MahqJzo4PL5kbX8u49f:-MahwN6S8iKywrZN46yt:b-rz4qvw) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/common.h#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, we don't use this anywhere, right? Can you remove this?
</blockquote></details>

Indeed, it's not used also in Database, so I removed it.
___
*[jni-binding/common.cpp, line 1 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-MahwxV3DfPYgI1cKcju:-Mai9A7TC8fUaVfIbm4O:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/common.cpp#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 8 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mahx-0A9-4-tLe6HqTr:-Mai9MNJ5SnGsg7r8P4W:bb8348i) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database.cpp#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since you're including common.h you don't need this two includes
</blockquote></details>

Done. Thanks, I removed all headers xD
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 147 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Macm33m2fdG8wK8YRw3:-Mai7PDeAWx8TIJrOU65:bs2yv0n) ([raw file](https://github.com/pmem/pmemkv-java/blob/b39a8eb987270d4740efba45f22fb276849861b5/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L147)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

What if NewDirectByteBuffer fails?
</blockquote></details>

Done. Indeed, I missed it.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 7 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mahx9pJ17MFaL7x543Z:-Mai9q3SAUhInsjdc_28:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

 same here
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 14 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai4I3hEycy29-iuKTd:-Mai9rjEE6oD57EnYGIx:b-s4f8hw) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we have to repeat the word `iterator` in this name? in C API we call this `pmemkv_write_iterator_new` so maybe something like this...?
</blockquote></details>

It's unavoidable due to naming generated through javah/javac -h
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 17 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai3grZ1RqMYGrz63cM:-MaiA74j0uyp5RiWcTZn:b-tkytjk) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

quite a long line, can you pls break it..?
</blockquote></details>

Done. I moved all after the qualifiers. The line takes now less than 120 characters. Unfortunately, moving this few short arguments to next line don't improve readability.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 29 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mahqloh4WBAMZyjVOEf:-MahxUdaAeJN1NaS5CPL:b-nvk3ef) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L29)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

since this is treated as pointer, shouldn't you return 0 (NULL)? Also either move this return to else or remove the else branch entirely (it's not really necessary since the first branch has returned).
</blockquote></details>

I've changed to value '0', but non-void function must return value.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 121 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai67rkCGZM_TXIHj9x:-Mai7af_7P4CtCXIY7Ie:b-p44stx) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L121)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in C++ `next` can also return NOT_FOUND
and what about possible other exceptions...?
</blockquote></details>

Right, I thought about it, but in `next` method we want to know the status of movement. In `next()` we care about "Was the move successful?".
E.g.
```
while(it.next) {
    System.out.println(it.read_range()); 
}
```
Anyway, when `next()` fails then iterator is invalid.
___
*[jni-binding/libpmemkv_jni.map, line 2 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-MahxIMV787TnXDrNJdh:-MaiAkKb1nC8ecXkYAvk:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/libpmemkv_jni.map#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2021
</blockquote></details>

Done.
___
*[jni-binding/libpmemkv_jni.map, line 36 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai2OxN7yUWCBaTM7XJ:-MaiAsIj2NUB0CK7Ac9S:bje62ly) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/libpmemkv_jni.map#L36)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I know they are not implemented yet, but there are already more new methods in the public API
</blockquote></details>

They are not implemented in Java and JNI side, so I decided to not expose it here.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 38 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai-E-j8ezLPNqDKDTu:-Mail-Z9ExoFuqxhuBZy:b-sv37xf) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hm... I guess, we're also missing descriptions for all public WriteIterator methods/ctors (pls mark as you did for the `iterator` member)

and as Igor mentioned, I believe, it should be marked that this is an still experimental feature
</blockquote></details>

Done.
I wrote the documentation for this methods.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 200 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai-xYs5Yd-_LddnYQm:-MaikuZo8xfShf55JNaV:b-hicu5o) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc1 [...]

2021-05-28 10:20 UTC, igchor requested changes
> Reviewed 4 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: 7 of 9 files reviewed, 15 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 147 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Macm33m2fdG8wK8YRw3:-MamCgR0CmAfGDgSqTn5:b-t86zlt) ([raw file](https://github.com/pmem/pmemkv-java/blob/b39a8eb987270d4740efba45f22fb276849861b5/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L147)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done. Indeed, I missed it.
</blockquote></details>

As discussed, please remove this if.


<!-- Sent from Reviewable.io -->

2021-05-28 10:27 UTC, KFilipek reviewed
> Reviewed 5 of 6 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: all files reviewed, 15 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 147 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Macm33m2fdG8wK8YRw3:-MamVnmZ3r0YSHS2AltO:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/b39a8eb987270d4740efba45f22fb276849861b5/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L147)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

As discussed, please remove this if.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-31 11:11 UTC, lukaszstolarczuk reviewed
> Reviewed 5 of 6 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 14 at r5](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mai4I3hEycy29-iuKTd:-Mb0jEm-7nBRPm7MG4ZX:bard2y8) ([raw file](https://github.com/pmem/pmemkv-java/blob/510887dc1c03fc189b1f8601dbf98db800d79370/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L14)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It's unavoidable due to naming generated through javah/javac -h
</blockquote></details>

ugh, but make sense, thx
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 4 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb13SU-78XEMGswCn8B:-Mb13SU19ZE6O8SNxSwY:b-lj60z8) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L4)):*
> ```cpp
> /* Copyright 2021, Intel Corporation */
> 
> // #include <io_pmem_pmemkv_Database_WriteIterator.h>
> ```

this is redundant, too
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 38 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb0xLnT8lhOsnfmbCwT:-Mb0xLnT8lhOsnfmbCwU:b19e530) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L38)):*
> ```Java
> 
> 	/**
> 	 * Binding for an pmemkv iterator API. Iterator provides methods to iterate over
> ```

`a pmemkv iterator`
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 39 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb11bhIEXMzg_oDbSfD:-Mb11bhIEXMzg_oDbSfE:b-366ktw) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L39)):*
> ```Java
> 	/**
> 	 * Binding for an pmemkv iterator API. Iterator provides methods to iterate over
> 	 * records in db. Object can be created only using Database method.
> ```

This/The object (?)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 39 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb11kZUD60NVR7DH9-L:-Mb11kZUD60NVR7DH9-M:b-1fg51w) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L39)):*
> ```Java
> 	/**
> 	 * Binding for an pmemkv iterator API. Iterator provides methods to iterate over
> 	 * records in db. Object can be created only using Database method.
> ```

using which DB method? pls add reference to method, so there will be link
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 41 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb0z0_6--dG9qb20kVm:-Mb0z0_6--dG9qb20kVn:b-80bsmz) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L41)):*
> ```Java
> 	 * records in db. Object can be created only using Database method.
> 	 * <p>
> 	 * Important: This is an experimental feature and should be not used in
> ```

`should not be used`
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 90 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb128p87gHJMI2q9vUa:-Mb128p87gHJMI2q9vUb:bwckpwp) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L90)):*
> ```Java
> 		 * status::OK, otherwise iterator is already on the last element and
> 		 * iterator.next() will return false.
> 		 * 
> ```

trailing space here
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 102 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb12MV3CsRadQiDcKnX:-Mb12MV3CsRadQiDcKnY:bn6g6rr) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L102)):*
> ```Java
> 		 * If the next record exists, returns true, otherwise false is returned and the
> 		 * iterator position is undefined.
> 		 * 
> ```

trailing space


<!-- Sent from Reviewable.io -->

2021-05-31 13:11 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: 7 of 9 files reviewed, 8 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 4 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb13SU-78XEMGswCn8B:-Mb1XSRY1LoHN7WY1Ru1:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this is redundant, too
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 38 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb0xLnT8lhOsnfmbCwT:-Mb1X_IO3zkj1Fii6tEi:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`a pmemkv iterator`
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 39 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb11bhIEXMzg_oDbSfD:-Mb1XcXEEgCAQ3DgCxsc:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

This/The object (?)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 39 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb11kZUD60NVR7DH9-L:-Mb1XniEEfmc5ul-hwPv:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L39)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

using which DB method? pls add reference to method, so there will be link
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 41 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb0z0_6--dG9qb20kVm:-Mb1XpdW48_-YPqni4E4:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`should not be used`
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 90 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb128p87gHJMI2q9vUa:-Mb1XwN41ptuq-FEk_jF:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L90)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

trailing space here
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 102 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/145#-Mb12MV3CsRadQiDcKnX:-Mb1Xwh_3loMIt873BJo:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/aeaa5f803a5e129c67466e2350c2793a102480a6/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L102)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

trailing space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-31 13:23 UTC, lukaszstolarczuk reviewed
pls just fix CI and after the 1.1 release we're good to go ;)

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145#-:-Mb1_ycN73k-7Dco78Ad:b-ffzm6y)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)



<!-- Sent from Reviewable.io -->

2021-05-31 13:42 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-06-01 16:54 UTC, igchor reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145#-:-Mb7Uvmi8lz8W14nj0J-:bnfp4nl)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-06-08 11:12 UTC, lukaszstolarczuk commented
please rebase and we can merge these goodies ;)

2021-06-08 15:42 UTC, KFilipek commented
> please rebase and we can merge these goodies ;)

I've rebased the PR.

2021-06-09 09:47 UTC, igchor approved these changes
> Reviewed 1 of 4 files at r3, 1 of 2 files at r7, 1 of 2 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-06-09 09:49 UTC, lukaszstolarczuk reviewed
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/145)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-06-09 09:50 UTC, merged