Seek implementation for Iterator API
pmem/pmemkv-java pull request #160
Opened 2021-05-28 14:24 UTC by KFilipek

- [JAVA] Implement Iterator API
Commits from: #156
- [JUnit] Add tests for Iterator API
- [Build system] Turn off building with pmemkv-1.3 or less
- [Java] Implement seek* functions for Iterator API

2021-06-14 13:04 UTC, KFilipek commented
PR successfully rebased.

2021-06-15 13:42 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 192 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McEtovj7mBnpkHTzRjb:-McEtovj7mBnpkHTzRjc:b8koshh) ([raw file](https://github.com/pmem/pmemkv-java/blob/8147c4bd3f3cfb01ea9f36cc7a0ee3b1b44a2040/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L192)):*
> ```cpp
>  * Signature: (J)Z
>  */
> JNIEXPORT jboolean JNICALL Java_io_pmem_pmemkv_Database_00024WriteIterator_iterator_1prev
> ```

Why you didn't implement that?


<!-- Sent from Reviewable.io -->

2021-06-17 16:52 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 192 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McEtovj7mBnpkHTzRjb:-McPsnJa4ozQgd1cMNrO:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/8147c4bd3f3cfb01ea9f36cc7a0ee3b1b44a2040/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L192)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why you didn't implement that?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-18 09:10 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McTMP141-diQiNjshAX:-McTMP141-diQiNjshAY:bnu16r2) (no related file):*
pls update `libpmemkv_jni.map`

---


<!-- Sent from Reviewable.io -->

2021-06-22 09:46 UTC, KFilipek reviewed
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McTMP141-diQiNjshAX:-Mcn6NGlCBInzL6PZrlc:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update `libpmemkv_jni.map`
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-06-22 15:06 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-06-23 05:54 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: all files reviewed, 10 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 32 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrQ3Pm8bBLDotkyC0g:-McrQ3Pm8bBLDotkyC0h:b-sb6jh5) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L32)):*
> ```Java
> 	}
> 
> 	private TreeMap<String, String> buildHashMap(int size) {
> ```

This map should have some gaps for the tests of `Eq` versions of seek
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 67 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrIqFL6uRvAf9R5ABX:-McrIqFL6uRvAf9R5ABY:b-l3vq7s) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L67)):*
> ```Java
> 	@Test
> 	public void readFewEntryTest() {
> 		TreeMap<String, String> hs = new TreeMap<String, String>();
> ```

You may use buildHashMap here. 
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 108 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrG4Co40ja1zMRLbnb:-McrFzGQ-e6jwlgVcuog:bo1px7w) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L108)):*
> ```Java
> 			while (it.isNext()) {
> 				assertTrue(it.next());
> 				assertTrue(hs.containsKey(byteBufferToString(it.key())));
> ```

It would be more reasonable to use Converter<String> instead of all those explicit conversions. This applys to all tests.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 125 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrHyHM-nQlDjnD7ZJB:-McrHsbMEw62V7PgUlqf:b-84u2ys) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L125)):*
> ```Java
> 		try (Database<ByteBuffer, ByteBuffer>.WriteIterator it = db.iterator()) {
> 			assertTrue(it.seekLower(stringToByteBuffer("key3")));
> 			if (ENGINE.equals("vsmap"))
> ```

ENGINE variable is immutable, so what's the point of checking it's value? 
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 145 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrM1ftAS9tkDoLthBd:-McrM1ftAS9tkDoLthBe:b6sd4gv) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L145)):*
> ```Java
> 
> 		try (Database<ByteBuffer, ByteBuffer>.WriteIterator it = db.iterator()) {
> 			assertTrue(it.seekLowerEq(stringToByteBuffer("key3")));
> ```

a is it seekLowerEq You should also check for key which is not present in db
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 146 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrJQVw0BwtCjnvpTug:-McrJCpT-kBm1Ift95B9:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L146)):*
> ```Java
> 		try (Database<ByteBuffer, ByteBuffer>.WriteIterator it = db.iterator()) {
> 			assertTrue(it.seekLowerEq(stringToByteBuffer("key3")));
> 			if (ENGINE.equals("vsmap"))
> ```

.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 167 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrJV_fApFzsc5kQbMi:-McrJV_fApFzsc5kQbMj:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L167)):*
> ```Java
> 		try (Database<ByteBuffer, ByteBuffer>.WriteIterator it = db.iterator()) {
> 			assertTrue(it.seekHigher(stringToByteBuffer("key3")));
> 			if (ENGINE.equals("vsmap"))
> ```

.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 188 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrPjph2apWlgi3XQKF:-McrPjph2apWlgi3XQKG:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L188)):*
> ```Java
> 		try (Database<ByteBuffer, ByteBuffer>.WriteIterator it = db.iterator()) {
> 			assertTrue(it.seekHigherEq(stringToByteBuffer("key3")));
> 			if (ENGINE.equals("vsmap"))
> ```

.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 189 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrPkwIEWDYOSAJcbJ5:-McrPkwIEWDYOSAJcbJ6:bo7fe1b) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L189)):*
> ```Java
> 			assertTrue(it.seekHigherEq(stringToByteBuffer("key3")));
> 			if (ENGINE.equals("vsmap"))
> 				assertTrue(byteBufferToString(it.key()).equals("key3"));
> ```

please, seek also for not present element.


<!-- Sent from Reviewable.io -->

2021-06-23 06:42 UTC, karczex commented
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 196 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrTxpVALqtRqotlvS_:-McrTxpVALqtRqotlvSa:b-lzxhav) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L196)):*
> ```cpp
>     auto status = w_it->prev();
> 
>     if (status == pmem::kv::status::OK or status == pmem::kv::status::NOT_FOUND) {
> ```

use `||` for consistency.

However I personally prefer `or` and `and` keywords :) 


<!-- Sent from Reviewable.io -->

2021-06-23 07:41 UTC, karczex reviewed
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: all files reviewed, 12 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 36 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrmNCQ0MEqhu0TYOwr:-McrmNCQ0MEqhu0TYOws:b-86ly8e) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L36)):*
> ```cpp
> JNIEXPORT jboolean JNICALL Java_io_pmem_pmemkv_Database_00024WriteIterator_iterator_1seek
>   (JNIEnv *env, jobject, jlong ptr, jobject key) {
>   auto w_it = reinterpret_cast<pmem::kv::db::write_iterator*>(ptr);
> ```

nit:
You may reduce amount of boilerplate code in seek* implementation by moving common code to separate function, and passing pmemkv call in lambda expression.
I made some prototype for this: 
` 
 https://github.com/karczex/pmemkv-java/commit/7f905ee7cecbdfc6f7c5202bb8b5a009dc8504a0
`

In fact it applies to many parts of this binding.


<!-- Sent from Reviewable.io -->

2021-06-24 12:15 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: 2 of 4 files reviewed, 11 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 196 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrTxpVALqtRqotlvS_:-McxGCvmCMq8CorU7oAf:b-7i9w4r) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L196)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

use `||` for consistency.

However I personally prefer `or` and `and` keywords :) 
</blockquote></details>

Done. Yeah, I changed it, but after my rebase fail I missed this change.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 32 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrQ3Pm8bBLDotkyC0g:-Mcxv6KcCRzBZjHorh-B:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L32)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This map should have some gaps for the tests of `Eq` versions of seek
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 67 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrIqFL6uRvAf9R5ABX:-Mcxv6jg7g_J1bcetaqA:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L67)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You may use buildHashMap here. 
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 108 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrG4Co40ja1zMRLbnb:-McxwVSL9V_KDnW2K_bb:bab6qdm) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L108)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It would be more reasonable to use Converter<String> instead of all those explicit conversions. This applys to all tests.
</blockquote></details>

I agree, can I change it in separate PR for all tests?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 125 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrHyHM-nQlDjnD7ZJB:-McxvF_BA5UgyVKluiVV:b2cwz6f) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L125)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

ENGINE variable is immutable, so what's the point of checking it's value? 
</blockquote></details>

It's true only in sorted engines. I've added it when somebody will change engine in the future then tests will be still correct. In not sorted engines we cannot rely on next or previous elements, just we found what we want .
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 145 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrM1ftAS9tkDoLthBd:-Mcxvl04Bzpim6Ys_mWf:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L145)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

a is it seekLowerEq You should also check for key which is not present in db
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 189 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrPkwIEWDYOSAJcbJ5:-Mcxvnkm7WXOAxbYyUHV:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L189)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

please, seek also for not present element.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-24 13:39 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: 2 of 4 files reviewed, 12 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 8 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McyETktEGpURpcjSwly:-McyETktEGpURpcjSwlz:b-a6chiu) ([raw file](https://github.com/pmem/pmemkv-java/blob/3d729ba54fece1140a59501cdb5d06ab99ec8da7/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L8)):*
> ```cpp
> /* Helper function for seek methods */
> template <typename Function>
> jboolean boilerplate_seek(JNIEnv *env, jlong ptr, Function lambda_fun, jobject key = nullptr) {
> ```

Why lambda_fun? This can be anything, not only lambda. Maybe just `fun?` Also please make it `Function && fun` to avoid copies if it's a functor class.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 50 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McyE9iD8uBMVvIjwuXB:-McyE9iD8uBMVvIjwuXC:bca2a4w) ([raw file](https://github.com/pmem/pmemkv-java/blob/3d729ba54fece1140a59501cdb5d06ab99ec8da7/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L50)):*
> ```cpp
> JNIEXPORT jboolean JNICALL Java_io_pmem_pmemkv_Database_00024WriteIterator_iterator_1seek
>   (JNIEnv *env, jobject, jlong ptr, jobject key) {
>   return boilerplate_seek(env, ptr, [](pmem::kv::db::write_iterator *w_it, const char* ckey) -> pmem::kv::status {
> ```

Ok, after seeing the implementation I think replacing lambda is not as simple as I told on scrum. You would have to pass:
```
std::bind(&iterator::seek, &_wit, std::placeholders::_1
```

instead of lambda. I'll leave the decision to you.


<!-- Sent from Reviewable.io -->

2021-06-24 15:14 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: 3 of 4 files reviewed, 12 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 8 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McyETktEGpURpcjSwly:-Mcy_KAY8T164fB5jQoc:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/3d729ba54fece1140a59501cdb5d06ab99ec8da7/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L8)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why lambda_fun? This can be anything, not only lambda. Maybe just `fun?` Also please make it `Function && fun` to avoid copies if it's a functor class.
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 50 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McyE9iD8uBMVvIjwuXB:-Mcy_M6uAcZOWAcVjYkz:bi6tenx) ([raw file](https://github.com/pmem/pmemkv-java/blob/3d729ba54fece1140a59501cdb5d06ab99ec8da7/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L50)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Ok, after seeing the implementation I think replacing lambda is not as simple as I told on scrum. You would have to pass:
```
std::bind(&iterator::seek, &_wit, std::placeholders::_1
```

instead of lambda. I'll leave the decision to you.
</blockquote></details>

I will read about it, I'm never using this stuff


<!-- Sent from Reviewable.io -->

2021-06-25 09:44 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: 2 of 4 files reviewed, 14 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 86 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1Y4F692pfyRc7dKXW:-Md1Y4F692pfyRc7dKXX:b-d4kt91) ([raw file](https://github.com/pmem/pmemkv-java/blob/ff7aa4a5382e688536d6cd5a912d5bbb49f8c38c/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L86)):*
> ```cpp
> JNIEXPORT jboolean JNICALL Java_io_pmem_pmemkv_Database_00024WriteIterator_iterator_1seek_1higher
>   (JNIEnv *env, jobject, jlong ptr, jobject key) {
>   // return boilerplate_seek(env, ptr, [](pmem::kv::db::write_iterator *w_it, const char* ckey) -> pmem::kv::status {
> ```

remove this comment?
___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 111 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1Y75G-Gh0JJzZZM9N:-Md1Y75G-Gh0JJzZZM9O:b-54x09r) ([raw file](https://github.com/pmem/pmemkv-java/blob/ff7aa4a5382e688536d6cd5a912d5bbb49f8c38c/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L111)):*
> ```cpp
> JNIEXPORT jboolean JNICALL Java_io_pmem_pmemkv_Database_00024WriteIterator_iterator_1seek_1to_1first
>   (JNIEnv *env, jobject, jlong ptr) {
>     return boilerplate_seek(env, ptr, [](pmem::kv::db::write_iterator *w_it, const char* ckey) -> pmem::kv::status {
> ```

nit: you can check if this works without `-> pmem::kv::status`It would be slightly shorter.


<!-- Sent from Reviewable.io -->

2021-06-25 10:00 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: 3 of 4 files reviewed, 13 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 86 at r7](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1Y4F692pfyRc7dKXW:-Md1Yk2kC1ROnRXb6cF7:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/ff7aa4a5382e688536d6cd5a912d5bbb49f8c38c/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L86)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

remove this comment?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-25 12:01 UTC, lukaszstolarczuk reviewed
> Reviewed 1 of 4 files at r3, 1 of 2 files at r6, 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: all files reviewed, 19 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 58 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1wHM_3E2Z7gr0I0aC:-Md1wHM_3E2Z7gr0I0aD:b-oocsii) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L58)):*
> ```Java
> 		}
> 
> 		/**
> ```

pls use `@param` annotation

(pls apply in all descriptions)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 63 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1v-OA5XoUP0HgP21r:-Md1v-OA5XoUP0HgP21s:bif35r2) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L63)):*
> ```Java
> 		 * If the record is present and no errors occurred, returns true. If the record
> 		 * does not exist, false is returned and the iterator position is undefined. It
> 		 * internally aborts all changes made to an element previously pointed by the
> ```

aborts all *uncommitted* changes

(pls apply in all descriptions)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 67 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1wRGGAxrW1szumB3I:-Md1wRGH5tki3ONfUT0h:b-lqoskc) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L67)):*
> ```Java
> 		 *
> 		 * @return true if success, false otherwise
> 		 * @throws DatabaseException
> ```

throws when?

(pls apply in all descriptions)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 68 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1uT_rCEYUj3tg7LGC:-Md1uT_rCEYUj3tg7LGD:b-e21s5n) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L68)):*
> ```Java
> 		 * @return true if success, false otherwise
> 		 * @throws DatabaseException
> 		 */
> ```

pls add `@since 1.2.0` to all these new methods and the class
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 75 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1tguK5sXYkrLFpnw0:-Md1tguK5sXYkrLFpnw1:bttztgw) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L75)):*
> ```Java
> 
> 		/**
> 		 * Changes iterator position to the record with key lower than given key.
> ```

to **a** record with **a** key (...) **the** given key.

(pls apply in all descriptions, incl. above one)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 142 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1y5nM09KmIJA9Z5p0:-Md1y5nM09KmIJA9Z5p1:b-d449qw) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L142)):*
> ```Java
> 		/**
> 		 * Changes iterator position to the first record.
> 		 *
> ```

pls extend these two descriptions; when it can return false?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 125 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrHyHM-nQlDjnD7ZJB:-Md2-PiCCmFaktQSWrnp:bzbfin3) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L125)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It's true only in sorted engines. I've added it when somebody will change engine in the future then tests will be still correct. In not sorted engines we cannot rely on next or previous elements, just we found what we want .
</blockquote></details>

If we ever going to change these tests to support other engines, it will be a bigger change. Right now you want to make these tests work just for one of our sorted engines, which is not quite a good approach, in my opinion.

anyway, I believe the above line:
`assertTrue(it.seekLower(stringToByteBuffer("key3")));`
will (at least should) return false when called for unsorted engine. (it should return `not_supported`)

I'd personally remove this check here and verify if it won't work for unsorted engines (even once, not necessarily as a sep. test, for now)
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 35 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1z1SQ5tKMm7R05P29:-Md1z1SR0OhEEm9Fz9if:b-sm9nis) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L35)):*
> ```Java
> 		TreeMap<String, String> hs = new TreeMap<String, String>();
> 		int seed = 4;
> 		for (int i = 0; i < 10; i++) {
> ```

10? did you mean `size`?


<!-- Sent from Reviewable.io -->

2021-06-25 13:47 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: all files reviewed, 12 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, line 50 at r6](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McyE9iD8uBMVvIjwuXB:-Md2M5XD7hA9aas0OJRL:b-t3gpqc) ([raw file](https://github.com/pmem/pmemkv-java/blob/3d729ba54fece1140a59501cdb5d06ab99ec8da7/jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp#L50)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I will read about it, I'm never using this stuff
</blockquote></details>

@igchor IMHO it's less readable than lambda. 
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 108 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrG4Co40ja1zMRLbnb:-Md2Nz-V7O9mExU1U4sA:bk0522s) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L108)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I agree, can I change it in separate PR for all tests?
</blockquote></details>

Sure. Just leave some XXX to not forgot. 


<!-- Sent from Reviewable.io -->

2021-06-25 16:28 UTC, KFilipek reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: 2 of 4 files reviewed, 12 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 58 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1wHM_3E2Z7gr0I0aC:-Md2konIDvg0zAutPdRp:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls use `@param` annotation

(pls apply in all descriptions)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 63 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1v-OA5XoUP0HgP21r:-Md2l0096tKPJiD12eHA:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L63)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

aborts all *uncommitted* changes

(pls apply in all descriptions)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 67 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1wRGGAxrW1szumB3I:-Md2l3u21K_Mtavi7Vna:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

throws when?

(pls apply in all descriptions)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 68 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1uT_rCEYUj3tg7LGC:-Md2lRoqAo-O6hlKE72t:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add `@since 1.2.0` to all these new methods and the class
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 75 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1tguK5sXYkrLFpnw0:-Md2lx0S6uZRFw9PMFPo:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L75)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

to **a** record with **a** key (...) **the** given key.

(pls apply in all descriptions, incl. above one)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 142 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1y5nM09KmIJA9Z5p0:-Md2oxJgDwFL7A63KDHv:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L142)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls extend these two descriptions; when it can return false?
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 108 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrG4Co40ja1zMRLbnb:-Md2hCf-7IHxbfX08nZB:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L108)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Sure. Just leave some XXX to not forgot. 
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 125 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrHyHM-nQlDjnD7ZJB:-Md2rIeB6ufXxc3u71EP:b7b5ajz) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L125)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

If we ever going to change these tests to support other engines, it will be a bigger change. Right now you want to make these tests work just for one of our sorted engines, which is not quite a good approach, in my opinion.

anyway, I believe the above line:
`assertTrue(it.seekLower(stringToByteBuffer("key3")));`
will (at least should) return false when called for unsorted engine. (it should return `not_supported`)

I'd personally remove this check here and verify if it won't work for unsorted engines (even once, not necessarily as a sep. test, for now)
</blockquote></details>

It should be solved at the pmemkv layer, not by bindings. Generally I agree that "not_supported" exception or something is a good approach. For now I will remove checking.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 35 at r9](https://reviewable.io/reviews/pmem/pmemkv-java/160#-Md1z1SQ5tKMm7R05P29:-Md2hGO-6H95aoJawxjp:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/c23874eac8d0ead026f4eb6b03c65d32ad9aa48c/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

10? did you mean `size`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-28 06:28 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 52 at r10](https://reviewable.io/reviews/pmem/pmemkv-java/160#-MdGEtdT470j40Z8DyMb:-MdGEtdU8rJ5JCTY8T_Q:b-fnde8k) ([raw file](https://github.com/pmem/pmemkv-java/blob/d0b6574d390070feb136cb4ca477f2bf25b37298/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L52)):*
> ```Java
> 		 * @param database_handle
> 		 *            handle to database pointer
> 		 */
> ```

since 1.2.0
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 388 at r10](https://reviewable.io/reviews/pmem/pmemkv-java/160#-MdGFM3yEZhjx1OrQnzG:-MdGFM3yEZhjx1OrQnzH:b-7jfxkb) ([raw file](https://github.com/pmem/pmemkv-java/blob/d0b6574d390070feb136cb4ca477f2bf25b37298/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L388)):*
> ```Java
> 	 * @throws DatabaseException
> 	 *             or derived class that matches pmemkv's status.
> 	 */
> ```

since
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 125 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrHyHM-nQlDjnD7ZJB:-MdGH2tn0NgqyW2P0qAw:b5dk4tv) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L125)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It should be solved at the pmemkv layer, not by bindings. Generally I agree that "not_supported" exception or something is a good approach. For now I will remove checking.
</blockquote></details>

**It is** solved at the pmemkv layer - when I said "it should return" I meant, we have to check if that's happening here, in java ;)
so, as I said previously, pls verify (at least once) if that's true


<!-- Sent from Reviewable.io -->

2021-06-28 12:44 UTC, KFilipek reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 52 at r10](https://reviewable.io/reviews/pmem/pmemkv-java/160#-MdGEtdT470j40Z8DyMb:-MdGy4AR8Yx_GCpHwcA4:b921wtz) ([raw file](https://github.com/pmem/pmemkv-java/blob/d0b6574d390070feb136cb4ca477f2bf25b37298/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since 1.2.0
</blockquote></details>

It's not public API, but I've added it
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 388 at r10](https://reviewable.io/reviews/pmem/pmemkv-java/160#-MdGFM3yEZhjx1OrQnzG:-MdHdJLw5F4nFklK-ne7:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/d0b6574d390070feb136cb4ca477f2bf25b37298/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L388)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

since
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java, line 125 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/160#-McrHyHM-nQlDjnD7ZJB:-MdHdKVm13i2V_K1PhZp:b-p2l5jy) ([raw file](https://github.com/pmem/pmemkv-java/blob/2aba6ba8cfb3188253c62cbfb847456f9327bfb7/pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java#L125)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

**It is** solved at the pmemkv layer - when I said "it should return" I meant, we have to check if that's happening here, in java ;)
so, as I said previously, pls verify (at least once) if that's true
</blockquote></details>

Done. I've added test for cmap and it throws exception.


<!-- Sent from Reviewable.io -->

2021-06-28 12:58 UTC, karczex reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160#-:-MdHgc0UEBuez7D5xED8:bnfp4nl)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-06-28 13:18 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160#-:-MdHlIuq92EG5Qon3Eq0:bnfp4nl)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)



<!-- Sent from Reviewable.io -->

2021-06-28 14:07 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/160#-:-MdHwXZ0-aG6i-JDY4uj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)



<!-- Sent from Reviewable.io -->

2021-06-28 14:08 UTC, merged