[Fix] Align exception checking to JNI guidelines
pmem/pmemkv-java pull request #163
Opened 2021-06-01 22:17 UTC by KFilipek

### PR description:
This PR fixes #159 and also introduce proper handling of exceptions as an example.
Changes was tested by adding `env->ThrowNew(class(java.lang.OutOfMemoryError), msg);` to simulate error in `env->NewDirectByteBuffer` and tests crashed as expected.
Bonus:
There is need to check when and why the `ExceptionCheck() == JNI_TRUE` is a true.

### Commit description:
This commit introduces proper handling of exceptions
and add test as example how to handle exception with specified class.
Fixes #159

2021-06-02 07:24 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAaaA2DmZ4LoDMi7VE:-MbAaaA3EKpWVkXsyQot:b-3nw17s) (no related file):*
what about https://github.com/pmem/pmemkv-java/issues/157

---
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 233 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAZHDX-iuAU3JjL8fc:-MbAZHDX-iuAU3JjL8fd:bv3ymt3) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/jni-binding/io_pmem_pmemkv_Database.cpp#L233)):*
> ```cpp
>         c->env->DeleteLocalRef(valuebuf);
>     }
>     if( c->env->ExceptionOccurred()) {
> ```

fix here pls
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 408 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAZbRyEN7KncTmWpTe:-MbAZbRyEN7KncTmWpTf:b-hmc2qr) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L408)):*
> ```Java
> 	 *            Function to be called for each specified key/value pair.
> 	 * @throws DatabaseException
> 	 *             with pmemkv return status.
> ```

add `throws` description here


<!-- Sent from Reviewable.io -->

2021-06-02 09:07 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @KFilipek)

___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 156 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAyRWq6WyF6uRRVem4:-MbAyRWq6WyF6uRRVem5:b-vkcv09) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L156)):*
> ```Java
> 	 * @throws OutOfMemoryException
> 	 *             Exception will be thrown when data cannot be allocated in DRAM.
> 	 * @since 1.0
> ```

Please add info that user exception will be rethrown 


<!-- Sent from Reviewable.io -->

2021-06-02 09:59 UTC, karczex reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @KFilipek)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 174 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbB7zbZ8k-xPNaJLieI:-MbB7zbZ8k-xPNaJLieJ:b3rwj9i) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L174)):*
> ```Java
> 		try {
> 			db.getAll((k, v) -> {
> 				throw new RuntimeException("Inner exception");
> ```

In this test you should throw CustomException to avoid catching very general RuntimeException by mistake.  Just like in exceptionInGet()
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 183 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbB9Bi-BlIpmn0JNfBv:-MbB9Bi-BlIpmn0JNfBw:b-2qbddv) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L183)):*
> ```Java
> 
> 	@Test(expected = StoppedByCallbackException.class)
> 	public void exceptionStoppedByCallbackInGetAllTest() {
> ```

You should rather fix exceptionInGetAllTest than adding this test.


<!-- Sent from Reviewable.io -->

2021-06-02 12:09 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 167 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAez2b4BID-hFUfLy6:-MbB6s1825EdOTNE_Y9M:b-3slylm) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/jni-binding/io_pmem_pmemkv_Database.cpp#L167)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: What about those calls? Can they fail? If so, we should probably handle that as well. If not (or it can only happen due to bug on our side) we could add some asserts here.
</blockquote></details>

GetDirectBufferAddress will not set exception by `env->NewThrow()`
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 233 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAZHDX-iuAU3JjL8fc:-MbBCmAs4GVVHhb3RNkH:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/jni-binding/io_pmem_pmemkv_Database.cpp#L233)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

fix here pls
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 243 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAgLJ048OtL50fFPAD:-MbBCunaCUBNuHN0Dxsj:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/jni-binding/io_pmem_pmemkv_Database.cpp#L243)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why we don't have `if (env->ExceptionCheck() == JNI_TRUE) return;` here?
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 156 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAyRWq6WyF6uRRVem4:-MbBHAyfDmkkJwl6XwZO:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L156)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add info that user exception will be rethrown 
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 408 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAZbRyEN7KncTmWpTe:-MbBHJNyERfhD5NwGdXb:b-abffa7) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L408)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add `throws` description here
</blockquote></details>

Done. I'm not sure we want to add `throws CustomException` or something similar, because user can throw exception with own type, so I will add Exception class as a base class for custom exception.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 174 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbB7zbZ8k-xPNaJLieI:-MbBIP-i9OZDU0HmpWSe:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L174)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

In this test you should throw CustomException to avoid catching very general RuntimeException by mistake.  Just like in exceptionInGet()
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 182 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAgWn72EnAbfAZ43h8:-MbBIBq3-v3Q0ehWRH22:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L182)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I thought we agreed that user should get here the exception which he threw (RuntimeException in this case), similar as in exceptionInGet().  In other words, StoppedByCallbackException would not be used anymore.
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 183 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbB9Bi-BlIpmn0JNfBv:-MbBbxEGDmQNUmEoc4i-:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L183)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You should rather fix exceptionInGetAllTest than adding this test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-02 12:18 UTC, igchor requested changes
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 125 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBdwEQ3yqzsA9loNPw:-MbBdwEQ3yqzsA9loNPx:bad60e9) ([raw file](https://github.com/pmem/pmemkv-java/blob/68a30fc557bcaa65e6b008def74893e45a235534/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L125)):*
> ```Java
> 					});
> 				} catch (Exception e) {
> 				}
> ```

Is this necessary?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 161 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBdxtS0NGz1Lhf3y2p:-MbBdxtS0NGz1Lhf3y2q:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/68a30fc557bcaa65e6b008def74893e45a235534/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L161)):*
> ```Java
> 						assertEquals(v, sb.substring(0, x + 1));
> 					});
> 				} catch (Exception e) {
> ```

.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 171 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBdy9PE5Nn0T9SKclz:-MbBdy9PE5Nn0T9SKcm-:b3kqx) ([raw file](https://github.com/pmem/pmemkv-java/blob/68a30fc557bcaa65e6b008def74893e45a235534/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L171)):*
> ```Java
> 						assertEquals(byteBufferToString(v), sb.substring(0, x + 1));
> 					});
> 				} catch (Exception e) {
> ```

.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 181 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBe3KJ8-imZRdNGb2f:-MbBe3KJ8-imZRdNGb2g:b-90w29n) ([raw file](https://github.com/pmem/pmemkv-java/blob/68a30fc557bcaa65e6b008def74893e45a235534/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L181)):*
> ```Java
> 
> 	@Test
> 	public void exceptionInGetKeysTest() {
> ```

Can you convert those other tests as well? We should make sure all get_* function are covered with such test


<!-- Sent from Reviewable.io -->

2021-06-02 12:38 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 226 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAfPvW172rllsjjHKt:-MbBhcYh6dtTFeWb5RUw:bfw1s25) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/jni-binding/io_pmem_pmemkv_Database.cpp#L226)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Didn't we want to check for exception here, before calling next NewDirectByteBuffer?
</blockquote></details>

Check or Clear? If here we get garbage we don't know how to handle it
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 125 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBdwEQ3yqzsA9loNPw:-MbBhmvX6TTv2KVszWc2:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/68a30fc557bcaa65e6b008def74893e45a235534/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L125)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 161 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBdxtS0NGz1Lhf3y2p:-MbBhnIo8BDAvyGVS4te:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/68a30fc557bcaa65e6b008def74893e45a235534/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L161)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, line 171 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBdy9PE5Nn0T9SKclz:-MbBhnZB3p75vK352R0y:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/68a30fc557bcaa65e6b008def74893e45a235534/pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java#L171)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 181 at r2](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBe3KJ8-imZRdNGb2f:-MbBio6G0uB9OzR1Ufb0:b-zefqe0) ([raw file](https://github.com/pmem/pmemkv-java/blob/68a30fc557bcaa65e6b008def74893e45a235534/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L181)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Can you convert those other tests as well? We should make sure all get_* function are covered with such test
</blockquote></details>

I'm not sure that is what you want


<!-- Sent from Reviewable.io -->

2021-06-02 12:41 UTC, KFilipek reviewed
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: 2 of 4 files reviewed, 10 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAaaA2DmZ4LoDMi7VE:-MbBjL2n7Eop7rwOhYe3:byr8qtj) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what about https://github.com/pmem/pmemkv-java/issues/157
</blockquote></details>

I changed exceptions to CustomException after @karczex suggestion

---


<!-- Sent from Reviewable.io -->

2021-06-02 12:43 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163#-:-MbBjW-IChD3MxzUjjbo:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 226 at r1](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAfPvW172rllsjjHKt:-MbBj1rz3Od3Hb5tXbcw:b76vhvn) ([raw file](https://github.com/pmem/pmemkv-java/blob/6d65e187a530ee45cb92d1c5861340ca2c836f34/jni-binding/io_pmem_pmemkv_Database.cpp#L226)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Check or Clear? If here we get garbage we don't know how to handle it
</blockquote></details>

Just check I think it's OK right now.


<!-- Sent from Reviewable.io -->

2021-06-02 13:48 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 4 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: all files reviewed, 12 unresolved discussions (waiting on @karczex and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAaaA2DmZ4LoDMi7VE:-MbBym3gA4sdThh27KoA:b1ek8ao) (no related file):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I changed exceptions to CustomException after @karczex suggestion
</blockquote></details>

you can add `Fixes #157` into commit msg

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBxrtNCSPWGsZjkqKa:-MbBxrtNCSPWGsZjkqKb:b-onuali) (no related file):*
in the commit msg you can drop `This commit` part; and actually, you can re-phrase it since you don't add new test anymore

---
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 48 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBrES5BlCDItdXatl3:-MbBrES5BlCDItdXatl4:b-82ntkz) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/jni-binding/io_pmem_pmemkv_Database.cpp#L48)):*
> ```cpp
>         }
>         env->ThrowNew(exception_class, msg);
>         env->DeleteLocalRef(exception_class);
> ```

if this is needed pls add it also in the above override of this function
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 119 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBt2qIDBKz5PJyUUbi:-MbBt2qIDBKz5PJyUUbj:bsi48em) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/jni-binding/io_pmem_pmemkv_Database.cpp#L119)):*
> ```cpp
>     // OutOfMemoryError may occurr
>     if (jobject valuebuf = c->env->NewDirectByteBuffer(const_cast<char*>(v), vb)) {
>         // Rerise exception
> ```

shouldn't we also check for an exception here, and return early?
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 251 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBsYkV8ESOVrMZtYeh:-MbBsYkV8ESOVrMZtYei:bphckay) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/jni-binding/io_pmem_pmemkv_Database.cpp#L251)):*
> ```cpp
>     auto status = engine->get_all(Callback_get_all_buffer, &cxt);
>     if (env->ExceptionCheck() == JNI_TRUE)
>         return; // Propagate exception raised by CallStaticVoidMethod()
> ```

that's not entirely true - it may be also OOM thrown from `NewDirectByteBuffer`
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 156 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBu9No4yuJab4GwMiT:-MbBu9Np3jAfLqsPLxe7:bridv5h) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L156)):*
> ```Java
> 	 * @throws OutOfMemoryError
> 	 *             Exception will be thrown when data cannot be allocated in DRAM.
> 	 * @throws Exception
> ```

look into CI - this is not proper javadoc syntax. I guess you'll have to just simply write "may rethrow exception thrown by user..." in the description (above the `@param` annotation)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 440 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBunXWCZhYHaWh6Gpc:-MbBunXWCZhYHaWh6Gpd:b-50q3p7) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L440)):*
> ```Java
> 	 *             with pmemkv return status.
> 	 * @throws ArrayIndexOutOfBoundsException
> 	 *             when internally fails.
> ```

when what internally fails?
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 71 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBw8iY2mHHAbdnwoJm:-MbBw8iY2mHHAbdnwoJn:b-k4f0wb) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd2a2281889e609c2556342fcc53a2cc69c128/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L71)):*
> ```Java
> 	@Test
> 	public void throwsExceptionOnStartWhenPathIsMissing() {
> 		Database<ByteBuffer, ByteBuffer> db = null;
> ```

this refactoring of tests has nothing to do with the commit message, pls move it into a separate commit 
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 77 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBvGCjEyZeQotkJCDy:-MbBvGCjEyZeQotkJCDz:b-umsx6) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd2a2281889e609c2556342fcc53a2cc69c128/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L77)):*
> ```Java
> 					.setSize(DEFAULT_DB_SIZE)
> 					.build();
> 			Assert.fail();
> ```

you can still have that line after the Builder command
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 84 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBvi2f0t6sVgb020XE:-MbBvi2f0t6sVgb020XF:b-3rv0li) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd2a2281889e609c2556342fcc53a2cc69c128/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L84)):*
> ```Java
> 		}
> 		assertTrue(exception_occured);
> 		assertNull(db);
> ```

and that assert could also stay in place, to make sure `db` is not assigned to anything

(both of these issues applies in all these DB tests)


<!-- Sent from Reviewable.io -->

2021-06-02 15:13 UTC, KFilipek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: 2 of 4 files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbAaaA2DmZ4LoDMi7VE:-MbC1MOt3KfIqvzFFz4d:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can add `Fixes #157` into commit msg
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBxrtNCSPWGsZjkqKa:-MbC1TvTAzNIrRkVOjYA:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in the commit msg you can drop `This commit` part; and actually, you can re-phrase it since you don't add new test anymore
</blockquote></details>

Done.

---
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 48 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBrES5BlCDItdXatl3:-MbC1hoT92fKbpf3CD7_:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/jni-binding/io_pmem_pmemkv_Database.cpp#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if this is needed pls add it also in the above override of this function
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 119 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBt2qIDBKz5PJyUUbi:-MbC1kb77X1pwy39Y20B:b-a28ury) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/jni-binding/io_pmem_pmemkv_Database.cpp#L119)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't we also check for an exception here, and return early?
</blockquote></details>

If `c->env->NewDirectByteBuffer()` fails a value returned is NULL, so the body of `if` statement will be skipped
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 251 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBsYkV8ESOVrMZtYeh:-MbC311y7uZLXNVhnv69:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/jni-binding/io_pmem_pmemkv_Database.cpp#L251)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's not entirely true - it may be also OOM thrown from `NewDirectByteBuffer`
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 156 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBu9No4yuJab4GwMiT:-MbC9xLaBRBqE5ybfMKI:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L156)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

look into CI - this is not proper javadoc syntax. I guess you'll have to just simply write "may rethrow exception thrown by user..." in the description (above the `@param` annotation)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 440 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBunXWCZhYHaWh6Gpc:-MbC9zAh1KBQf2HiDmTG:bciyluq) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L440)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

when what internally fails?
</blockquote></details>

It's an exception thrown by SetByteArrayRegion, when the Buffer is longer than ByteArray you created in `callback_get_byte_array`(io_pmem_pmemkv_Database.cpp:315).
Another option is to convert this exception into pmemkv exception, but then we confront with the similar issue to OutOfMemoryError
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 71 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBw8iY2mHHAbdnwoJm:-MbCHLW-7IAXuFy8BpdF:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd2a2281889e609c2556342fcc53a2cc69c128/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L71)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this refactoring of tests has nothing to do with the commit message, pls move it into a separate commit 
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 77 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBvGCjEyZeQotkJCDy:-MbCAy_X-CfG-rU10YM7:b-dnczc7) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd2a2281889e609c2556342fcc53a2cc69c128/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L77)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can still have that line after the Builder command
</blockquote></details>

In this approach assert will fail if you throw nothing or something different. Adding `Assert.fail()` just make noise and produce shit instead of clear message like: "Test throw nothing, but expected: some_type_of_exception"
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 84 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBvi2f0t6sVgb020XE:-MbCCfHNEDc50ME7dNRZ:bst6psa) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd2a2281889e609c2556342fcc53a2cc69c128/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L84)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

and that assert could also stay in place, to make sure `db` is not assigned to anything

(both of these issues applies in all these DB tests)
</blockquote></details>

It makes no sense.
Null always will be null.


<!-- Sent from Reviewable.io -->

2021-06-02 15:38 UTC, karczex commented
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 152 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbCL4g7CGnWQ2b7w-46:-MbCL4g7CGnWQ2b7w-47:b-y65eo) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L152)):*
> ```Java
> 	@Test
> 	public void exceptionInTheMiddleOfGetKeysTest() {
> 		int exception_counter = 0;
> ```

exception_counter is never used.


<!-- Sent from Reviewable.io -->

2021-06-04 05:49 UTC, lukaszstolarczuk reviewed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: all files reviewed, 11 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 119 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBt2qIDBKz5PJyUUbi:-MbKVYCJCjNo908o-wEQ:b-i0exla) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/jni-binding/io_pmem_pmemkv_Database.cpp#L119)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

If `c->env->NewDirectByteBuffer()` fails a value returned is NULL, so the body of `if` statement will be skipped
</blockquote></details>

hmm.. true, then pls remove these comments here; We make sure to re-rise the exception in other functions.
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 343 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbKWBzs4382ynHiaKhQ:-MbKWBztBeAJp9MXHyO4:bhlhwox) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/jni-binding/io_pmem_pmemkv_Database.cpp#L343)):*
> ```cpp
>     ContextGetByteArray cxt = ContextGetByteArray(env);
>     auto status = engine->get(cppkey, callback_get_byte_array, &cxt);
>     if (env->ExceptionCheck() == JNI_TRUE) return nullptr;
> ```

pls add a comment here (and one function above) to also state we do that `return` to "Propagate an exception"
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 440 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBunXWCZhYHaWh6Gpc:-MbKX-k935d5mk8Dh14_:b-xgtwoh) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L440)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It's an exception thrown by SetByteArrayRegion, when the Buffer is longer than ByteArray you created in `callback_get_byte_array`(io_pmem_pmemkv_Database.cpp:315).
Another option is to convert this exception into pmemkv exception, but then we confront with the similar issue to OutOfMemoryError
</blockquote></details>

I'm just saying this comment does not tell much - "when internally fails" is not even proper English, you're missing the "what" part (a subject of the sentence) at least ;)
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 149 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbKWZpC0RbD0hkSxAq5:-MbKWZpC0RbD0hkSxAq6:b-tqwiq0) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L149)):*
> ```Java
> 	/**
> 	 * Executes callback function for every key stored in the pmemkv datastore. Any
> 	 * Exception thrown by user from callback will be propagated.
> ```

`Exception` here is just a regular noun, pls make it lowecase
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 149 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbKWlVY2zg59YgolwWW:-MbKWlVY2zg59YgolwWX:b-6l6vxe) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L149)):*
> ```Java
> 	/**
> 	 * Executes callback function for every key stored in the pmemkv datastore. Any
> 	 * Exception thrown by user from callback will be propagated.
> ```

by **the** user
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 168 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbKWshz7hkXiD_v5boL:-MbKWshz7hkXiD_v5boM:b-c894nc) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L168)):*
> ```Java
> 	 * <p>
> 	 * Comparison mechanism is based on binary comparison of bytes - by a function
> 	 * equivalent to std::string::compare in C++. Any Exception thrown by user from
> ```

. (applies everywhere)
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 84 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBvi2f0t6sVgb020XE:-MbKYW_r5jt-FBLQSDLR:bm8ty8n) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd2a2281889e609c2556342fcc53a2cc69c128/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L84)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It makes no sense.
Null always will be null.
</blockquote></details>

aren't tests designed to check expected behavior...? ;) we know it should behave like this, but we want to confirm it. In my opinion, db check should stay in place
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 71 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbKY98h0t2QXJZ2u02W:-MbKY98h0t2QXJZ2u02X:bmqkz5x) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L71)):*
> ```Java
> 	@Test
> 	public void throwsExceptionOnStartWhenPathIsMissing() {
> 		Exception exception = assertThrows(InvalidArgumentException.class, () -> {
> ```

you don't use the `exception` variable, I guess you can get rid of it (here and in the next 4 functions)


<!-- Sent from Reviewable.io -->

2021-06-07 12:18 UTC, KFilipek reviewed
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: 1 of 4 files reviewed, 11 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 119 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBt2qIDBKz5PJyUUbi:-Mb_yfrv9nX4FwCiP13X:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/jni-binding/io_pmem_pmemkv_Database.cpp#L119)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. true, then pls remove these comments here; We make sure to re-rise the exception in other functions.
</blockquote></details>

Done.
___
*[jni-binding/io_pmem_pmemkv_Database.cpp, line 343 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbKWBzs4382ynHiaKhQ:-Mb_yywP6vxutZXgk5SW:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/jni-binding/io_pmem_pmemkv_Database.cpp#L343)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a comment here (and one function above) to also state we do that `return` to "Propagate an exception"
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 440 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBunXWCZhYHaWh6Gpc:-MbaME2y7pXXFvoJeM4b:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/a320494521f0037ec734be6fb4f4a01d4c772f66/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L440)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm just saying this comment does not tell much - "when internally fails" is not even proper English, you're missing the "what" part (a subject of the sentence) at least ;)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 149 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbKWZpC0RbD0hkSxAq5:-Mba3Qt61C0rEfGog2dL:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L149)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`Exception` here is just a regular noun, pls make it lowecase
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 149 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbKWlVY2zg59YgolwWW:-Mba3Ux9-jG_-laACERe:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L149)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

by **the** user
</blockquote></details>

Done.
___
*[pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, line 168 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbKWshz7hkXiD_v5boL:-Mba3_L75IxNQm2U5N-0:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java#L168)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (applies everywhere)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 84 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBvi2f0t6sVgb020XE:-Mba4op_149YVOF3ht8m:b-5aagy5) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd2a2281889e609c2556342fcc53a2cc69c128/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L84)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

aren't tests designed to check expected behavior...? ;) we know it should behave like this, but we want to confirm it. In my opinion, db check should stay in place
</blockquote></details>

Right, but also tests are not designed to test language itself.

https://docs.oracle.com/javase/specs/jls/se7/html/jls-18.html
The grammar precisely define the Expression:
```
Expression: 
    Expression1 [AssignmentOperator Expression1]

AssignmentOperator: 
    =
[more assignment operators]
```
When `Expression1` fails, rest of the `Expression` will never be executed and whole block will roll up.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 71 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbKY98h0t2QXJZ2u02W:-MbaJ8FC0CBPuWUJAjYc:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L71)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't use the `exception` variable, I guess you can get rid of it (here and in the next 4 functions)
</blockquote></details>

Done.
___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 152 at r4](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbCL4g7CGnWQ2b7w-46:-MbaJKCc9oLVRXPMshh7:b-896fix) ([raw file](https://github.com/pmem/pmemkv-java/blob/cffae7032326faf127c17ae0d51fc8a86687b4f7/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L152)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

exception_counter is never used.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-07 12:26 UTC, lukaszstolarczuk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163#-:-MbaQyhF-b4TNdybIVVj:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, line 84 at r3](https://reviewable.io/reviews/pmem/pmemkv-java/163#-MbBvi2f0t6sVgb020XE:-MbaQ3bCDmneqlZAWO4q:b-e7bzr1) ([raw file](https://github.com/pmem/pmemkv-java/blob/edfd2a2281889e609c2556342fcc53a2cc69c128/pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java#L84)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Right, but also tests are not designed to test language itself.

https://docs.oracle.com/javase/specs/jls/se7/html/jls-18.html
The grammar precisely define the Expression:
```
Expression: 
    Expression1 [AssignmentOperator Expression1]

AssignmentOperator: 
    =
[more assignment operators]
```
When `Expression1` fails, rest of the `Expression` will never be executed and whole block will roll up.
</blockquote></details>

I guess it's true, thx!


<!-- Sent from Reviewable.io -->

2021-06-07 12:30 UTC, igchor approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-java/163)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)



<!-- Sent from Reviewable.io -->

2021-06-07 12:43 UTC, merged